table=[
"48 48 196 2 ",
"   c None",
".  c black",
"X  c #060708",
"o  c #090A0B",
"O  c #070809",
"+  c #0F0F10",
"@  c #0E1012",
"#  c #111416",
"$  c #1B1D1E",
"%  c #14171A",
"&  c #181C20",
"*  c #1D2225",
"=  c #212224",
"-  c #22262A",
";  c #26282A",
":  c #282B2E",
">  c #232A32",
",  c #2C333A",
"<  c #383B3E",
"1  c #353C43",
"2  c #393E43",
"3  c #3A4249",
"4  c #3E4954",
"5  c #444749",
"6  c #474A4D",
"7  c #474E54",
"8  c #4A5259",
"9  c #54595E",
"0  c #4F5C69",
"q  c #565D65",
"w  c #59626A",
"e  c #5C6B79",
"r  c #586674",
"t  c #65686B",
"y  c #626E79",
"u  c #646C74",
"i  c #697279",
"p  c #73777B",
"a  c #76797B",
"s  c #3B7F9B",
"d  c #4E7E96",
"f  c #6E7D8B",
"g  c #687784",
"h  c #757B82",
"j  c #757E88",
"k  c #3A809D",
"l  c #388BA9",
"z  c #3F92AF",
"x  c #3797B9",
"c  c #2A96BA",
"v  c #5D8498",
"b  c #6F808F",
"n  c #73818F",
"m  c #6E8B9C",
"M  c #66899C",
"N  c #738391",
"B  c #7D8B99",
"V  c #7A8B98",
"C  c #428CA8",
"Z  c #4489A4",
"A  c #538BA2",
"S  c #4C92AD",
"D  c #5292AA",
"F  c #4899B6",
"G  c #549CB6",
"H  c #618EA1",
"J  c #6497AB",
"K  c #7797A7",
"L  c #57A2BD",
"P  c #66A3BD",
"I  c #76A3B7",
"U  c #379EC0",
"Y  c #3AA3C3",
"T  c #45A3C3",
"R  c #4CA5C4",
"E  c #43ABCA",
"W  c #4DACCA",
"Q  c #5DADC9",
"!  c #59A8C4",
"~  c #4DB2CF",
"^  c #55B1CD",
"/  c #5CB1CD",
"(  c #5AB6D1",
")  c #57BBD5",
"_  c #4AB5D1",
"`  c #68ACC6",
"'  c #68B2CD",
"]  c #71B4CC",
"[  c #6AB7D0",
"{  c #64BCD5",
"}  c #6BBBD4",
"|  c #61BFD8",
" . c #74BAD2",
".. c #7CBCD3",
"X. c #74ACC3",
"o. c #5FC2DB",
"O. c #64C4DC",
"+. c #6BC4DB",
"@. c #6DC8DE",
"#. c #74C3DA",
"$. c #73C9DE",
"%. c #7ACADF",
"&. c #7AC3D9",
"*. c #75CCE0",
"=. c #7CCEE1",
"-. c #818C96",
";. c #84919E",
":. c #83878B",
">. c #8594A1",
",. c #8A97A3",
"<. c #8D9AA6",
"1. c #899DA9",
"2. c #919EA9",
"3. c #919CA7",
"4. c #8CA2AD",
"5. c #96A2AD",
"6. c #9AA5AE",
"7. c #84A5B4",
"8. c #9BA6B1",
"9. c #9EAAB3",
"0. c #97ACB6",
"q. c #9BB0BB",
"w. c #A2ACB5",
"e. c #A3AEB8",
"r. c #A5B2BB",
"t. c #ABB5BD",
"y. c #AEB5BA",
"u. c #ADB1B6",
"i. c #87BDD3",
"p. c #AEB7C0",
"a. c #AFB8C1",
"s. c #B4BDC4",
"d. c #B8BEC5",
"f. c #83C5DA",
"g. c #84CBDE",
"h. c #8EC9DC",
"j. c #89C3D7",
"k. c #93CBDD",
"l. c #95C8DA",
"z. c #BBC2CA",
"x. c #BCC2C6",
"c. c #A4CEDE",
"v. c #A4C9D9",
"b. c #81CEE1",
"n. c #8BCFE1",
"m. c #84D1E3",
"M. c #8BD4E5",
"N. c #93D6E6",
"B. c #9CD4E3",
"V. c #97D8E7",
"C. c #97D9E8",
"Z. c #9BD9E8",
"A. c #9BD8E7",
"S. c #A3D4E3",
"D. c #ADD5E3",
"F. c #ABD9E6",
"G. c #A3DCEA",
"H. c #ABDEEB",
"J. c #A2D9E7",
"K. c #BBD9E5",
"L. c #B3DEEA",
"P. c #BADEE9",
"I. c #B5D9E6",
"U. c #ADE1ED",
"Y. c #B4E2EE",
"T. c #BCE3ED",
"R. c #BFE7F0",
"E. c #C0C7CE",
"W. c #C1C8CF",
"Q. c #C5CCD2",
"!. c #C9CED4",
"~. c #CCD1D6",
"^. c #CED4D9",
"/. c #D1D6DB",
"(. c #D5DADE",
"). c #C2DDE8",
"_. c #D9DDE1",
"`. c #D7DCE0",
"'. c #C3E2EC",
"]. c #CAE4EE",
"[. c #DEE1E5",
"{. c #D9E8EF",
"}. c #D3E5EE",
"|. c #C2E7F0",
" X c #C4E8F1",
".X c #CDEAF2",
"XX c #DBEDF3",
"oX c #DCF0F5",
"OX c #E0E3E6",
"+X c #E3E6E9",
"@X c #E6E9EC",
"#X c #E8EBED",
"$X c #ECF6F9",
"%X c #EAF4F8",
"&X c #E3F2F6",
"*X c #FBFDFE",
"                                                    . . . . . . . .                             ",
"                                              . . X = 6 t a p t 5 $ . . .                       ",
"                                          . . ; p s._.+X#X#X#X#X+X[.y.i $ . .                   ",
"                                      . . = :.!.[.#X#X#X#X#X#X#X#X#X#X[.~.n % X .               ",
"                                    . . q z.[.@X+X+X_.Q.d.s.s.s.Q.[.+X+X@X[.x.5 . .             ",
"                                  . O j /.+X[.(.t.K d k Z S S Z s v >.s.[.[.[.^.t X .           ",
"                                . X :._.[.`.e.v C ..).$X*X*X*X*X%XI.] Z M t.[.[.(.u . .         ",
"                              . . p _._.Q.V C l.&X%X$X$X$X$X$X$X$X$X%XoXj.Z >.^.`.(.9 .         ",
"                              . 6 /.(.s.M ! ].XXXXXXXXoXoXoXoXoXoXoXoXXXXX'.G m W.(.~.: .       ",
"                            . # z.^.x.v ] ]..X]..X.X.X.X.X.X.X.X.X.X.X.X.X].'.L m W./.w.X .     ",
"                            . p ^.z.m ` P.P.T.T.T.T.|.R.R.|.R.R.R.R.T.T.T.T.T.I.L ;.!.~.7 .     ",
"                          . + E.~.1.G S.F.F.H.L.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.U.F.F.F.c.D 6.!.u.X     ",
"                          . t W.a.A j.B.S.S.J.G.G.U.H.U.U.U.U.U.U.U.G.U.J.J.J.S.B...M x.Q.< .   ",
"                          . 9.Q.1.L h.k.N.N.A.A.Z.Z.Z.G.G.Z.G.Z.Z.G.Z.Z.A.A.N.k.k.h.G 6.E.:..   ",
"                        . $ z.s.H  .f.g.n.M.N.V.C.C.C.C.C.C.C.C.A.N.A.N.N.N.M.g.g.f.! m z.s.X . ",
"                        . 6 z.r.D  .&.%.b.n.M.M.M.N.M.N.N.C.C.C.N.N.N.M.M.m.%.O.~ Y c A p.z.; . ",
"                        . t s.6.F ' } #.=.b.b.m.M.M.M.M.M.M.M.N.M.m.=.*.O.) ) _ Y Y U l u.s.5 . ",
"                        . h s.<.T ' { +.#.*.b.b.m.m.M.M.M.m.=.=.*.@.@.O.O.o.) ) _ E U l w.s.9 . ",
"                        . h t.1.T ^ { { +.*.=.=.b.=.=.=.=.*.=.*.*.*.*.@.@.O.O.) ~ E Y x 6.y.q . ",
"                        . h t.<.F W ^ { +.*.*.*.=.=.=.m.=.m.=.m.=.=.=.*.*.@.@.| ( W T x 9.y.q . ",
"                        . i e.5.x R ^ { +.$.=.=.=.m.m.M.M.M.M.M.m.m.m.m.=.*.$.O.( ^ T z e.e.8 . ",
"                        . q e.e.F W ( { #.*.b.m.M.M.M.N.N.C.N.M.N.M.M.M.n.=.$.+.{ ^ R S a.e.< . ",
"                        . < 9.s.D R / } #.=.m.M.N.C.C.Z.Z.G.Z.Z.C.C.V.M.M.n.=.#.{ Q R J p.9.$ . ",
"                        . # 8.r.K R / } #.b.M.V.C.Z.G.G.G.G.G.G.G.G.Z.C.N.m.g.#.[ Q R 4.e.,..   ",
"                          . j 8.e.G ' } &.g.N.A.G.G.H.U.U.U.U.U.U.G.G.Z.A.M.g. .[ Q D s.6.w .   ",
"                          . 2 2.s.K Q [ ..g.N.A.G.U.U.Y.Y.Y.R.Y.Y.U.U.G.A.k.g.&.[ ! 1.t.2.= .   ",
"                          . X B 5.s.G ' ..f.k.A.G.U.Y.R.R.|.R.R.R.Y.H.F.B.h.f. .' G z.2.i .     ",
"                          . . 1 ,.r.8.`  .f.k.B.H.Y.R.R.|. X X|.T.T.L.S.k.h...] P y.w.<.& .     ",
"                      . . ; - e <.,.z.4.X...h.B.S.L.P.'. X].]. X'.P.F.S.k.j...P 9.p.>.7 .       ",
"                    . . 2 <.V 8.d.2.,.z.8.X.i.l.c.D.P.).'.].].'.K.I.D.l.l.i.I r.s.;.u . .       ",
"                  . . 2 >.p.8.z.`.`.,.>.d.y.I l.c.I.K.).).].].).).K.D.c.i.I z.t.-.y o .         ",
"                . . 2 >.9.z.`.`.@X_.d.;.B w.~.e.7.c.).{.{.{.XXXX}.K.v.7.u.~.5.B r O .           ",
"              . . 2 >.9.d.^.+X`.`.z.9.y 8 V -.p.(.s.e.0.q.p.p.0.0.q.z./.e.V N 3 . .             ",
"            . . 2 >.9.d.^.[.#X`.t.<.N - . & r N V 3.p.Q.(.(././.z.p.1.N N 0 # . .               ",
"          . . 2 >.9.d.^.[.#X[.^.s.<.f * . . . & 7 g N b b b b N b b e 3 # . .                   ",
"        . . 2 ;.9.d.^.[.#X[.^.z.e.>.1 .       . . . @ - , 1 1 , * @ . . .                       ",
"      . . 1 B 6.d.^.[.#X[.^.z.9.>.1 . .             . . . . . . . .                             ",
"    . . , n 3.t.!._.#X[.^.z.9.,.1 . .                                                           ",
"  . . , g ;.9.d.^.[.[.^.d.9.,.1 . .                                                             ",
"  . > e N 3.r.E.^.`.!.d.e.>.1 . .                                                               ",
". & 0 g B 5.a.z.z.z.p.8.>.1 . .                                                                 ",
". > r f ;.8.p.p.r.e.2.-.1 . .                                                                   ",
". # e f ;.5.8.8.2.>.N , . .                                                                     ",
"  . 4 f B ;.>.-.N g , . .                                                                       ",
"  . X w f f f g e > . .                                                                         ",
"    . X 4 e r 0 > . .                                                                           ",
"      . . # > & . .                                                                             ",
"          . . .                                                                                 "
]