table=[
"48 48 111 2 ",
"   c black",
".  c #0A0900",
"X  c #050A0D",
"o  c #161300",
"O  c #1A1700",
"+  c #1E1C00",
"@  c #060F13",
"#  c #051217",
"$  c #091216",
"%  c #061219",
"&  c #0A151A",
"*  c #0C181C",
"=  c #191716",
"-  c #191919",
";  c #271F00",
":  c #3D3100",
">  c #0D1D23",
",  c #0F2228",
"<  c #11242C",
"1  c #13282E",
"2  c #132A32",
"3  c #162F38",
"4  c #17313A",
"5  c #252525",
"6  c #2F2F2F",
"7  c gray20",
"8  c #563800",
"9  c #644400",
"0  c #615600",
"q  c #615800",
"w  c #6C5F00",
"e  c #61570B",
"r  c #143E54",
"t  c #1F424F",
"y  c #17465F",
"u  c #204451",
"i  c #234C5B",
"p  c #184861",
"a  c #275364",
"s  c #2A5A6C",
"d  c #2C5F71",
"f  c #31697F",
"g  c #626262",
"h  c DimGray",
"j  c #696A73",
"k  c #855700",
"l  c #875800",
"z  c #9C6B00",
"x  c #967A00",
"c  c #997B00",
"v  c #BE7C00",
"b  c #938100",
"n  c #988600",
"m  c #9A8800",
"M  c #A68600",
"N  c #B08E00",
"B  c #B49100",
"V  c #DE9800",
"C  c #E19200",
"Z  c #EC9A00",
"A  c #D5BC00",
"S  c #FFB300",
"D  c #FFBC00",
"F  c #D9C100",
"G  c #D9C31E",
"H  c #FFC000",
"J  c #FDCC00",
"K  c #FFD600",
"L  c #FFE100",
"P  c #FFEC00",
"I  c #FFF200",
"U  c yellow",
"Y  c #FFE41E",
"T  c #FFEA1E",
"R  c #FFF522",
"E  c #326B80",
"W  c #3A7C95",
"Q  c #3B7F98",
"!  c #3E849E",
"~  c #3F86A1",
"^  c #418AA5",
"/  c #428EAB",
"(  c #4390AC",
")  c #36ACEA",
"_  c #4EA7C8",
"`  c #54B4D7",
"'  c #55B5D9",
"]  c #57B9DE",
"[  c #55BAE0",
"{  c #59BDE3",
"}  c #3FCAFF",
"|  c #5CC5EC",
" . c #5DC8EF",
".. c #5EC8F1",
"X. c #46D7FF",
"o. c #47D9FF",
"O. c #61CFF9",
"+. c #63D3FD",
"@. c #66DAFF",
"#. c #68DFFF",
"$. c #6BE5FF",
"%. c #6DE9FF",
"&. c #70EFFF",
"*. c #72F4FF",
"=. c #79FFFF",
"-. c #979797",
";. c #9B9B9B",
":. c #9F9F9F",
">. c #A7A7A7",
",. c #CDCDCD",
"<. c none",
"6                                                       7 <.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.",
"  5 j e 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 w .   - <.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.",
"  h <.R P I I I I I I I I I I I I I I I I I I I I I U +     - <.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L K L L L I o ; B   - <.<.<.<.<.<.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L I o o I c   - <.<.<.<.<.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L U o o K L c   - <.<.<.<.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y K L L L L L L L L L L L L L L L L L L L L L I o o L J L c   - <.<.<.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L I o o L J J L c   - <.<.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L I O o P K K K P M   - <.<.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L I o . M x x x x N :   - <.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L I O                     -.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L P A F F F F F F V v   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L P P L P L P P D C   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L S C   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L S C   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y K L L L L L L L L L L L L L L L L L L L L L L L L L L L L L P S C   :.<.<.<.<.<.<.<.<.<.",
"  g <.T P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P I D Z   >.<.<.<.<.<.<.<.<.<.",
"  g <.G b m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m z l   g >.:.:.:.:.:.:.;.,.",
"  g <.&                                                                                         ",
"  g <.= @ | ` ` ' ' ' ' ' ' ` ` ' ' ] ] ' ' ' ' ' ' ' ' ] [ ' ' ' ' ' ' ] ' ] ] ] ] ] { [ ) r   ",
"  g <.= # &.@.@.@.@.@.@.@.@.@.@.#.&.+.| %.$.@.@.@.@.#.*.| { $.$.@.@.@.@.@.@.@.@.@.@.@.@.@.} p   ",
"  g <.= # %.+.+.+.+.@.` ` @.+.@.| $       W $.+.+.@.]         d %.+.$.&   %.+.+.+.+.$.$   X.y   ",
"  g <.= # %.+.+.+.+.$.X   $.@.@.    f ! *   W $.+.#.    ! ^ 4   ! #.%.*   f $.+.+.+.$.&   o.y   ",
"  g <.= # $.+.+.+.+.$.%   $.#.a   { $.$.*.&   %.@./   _ $.#.*.    $.$.>     ..@.+.+.$.*   X.y   ",
"  g <.= # %.+.+.+.+.$.%   %.$.*   &.+.+.#.W   [ $.!   { @.+.$.*   %.%.*     > *.+.+.%.*   o.y   ",
"  g <.= # %.+.+.+.+.%.&   %.$.2   *.+.+.@...i @.@.!   ] @.+.%.&   %.%.&   Q   / #.@.$.*   o.y   ",
"  g <.= # %.+.+.+.+.%.%   %.#.!   s *.$.#.@.#.+.@.!   ] @.+.%.&   %.%.&   =.    $.+.$.*   o.y   ",
"  g <.= # $.+.+.+.+.%.&   %.+.%.3       a @.@.+.#.!   ] @.+.%.&   %.%.&   %.'   t %.$.*   o.y   ",
"  g <.= # %.+.+.+.+.%.&   %.+.+.%.~ 2       ..@.#.!   ] @.+.$.&   %.%.&   $.%.u   ` &.&   o.p   ",
"  g <.= # %.+.+.+.+.%.%   %.+.@.#.#.$.%.{     %.#.!   ] @.+.$.&   %.%.&   $.@.$.    =.*   o.y   ",
"  g <.= # $.@.$.+.+.%.&   %.#.~ ^ @.+.+.$.f   ..$.!   ] @.+.%.&   %.%.&   %.+.#.(   W 1   o.y   ",
"  g <.= # &.^ 2 $.+.%.*   $.$.@   &.+.+.#.~   { #.!   [ @.+.%.*   %.%.&   $.+.+.&.>   $   o.y   ",
"  g <.= # *.a   #.$.*.    $.$.a   { $.#.*.&   $.#./   _ $.#.*.    $.%.&   %.+.+.@.O.      o.p   ",
"  g <.= # %.]   $ / 4   ! #.+.@.    E ! &     #.+.#.    Q ^ 4   ! #.$.&   $.+.+.+.$.f     o.y   ",
"  g <.= # %.$./       d $.O.+.@.| #       W %.@.+.@.]         d %.+.$.$   $.+.+.+.+.%.    X.y   ",
"  g <.= # %.@.$.%.{ $.%.@.@.@.@.#.*.+.| %.$.@.@.@.@.#.&.| { $.%.@.@.@.@.@.@.@.@.@.@.@.@.@.} p   ",
"  g <.= @ | ` ` ' ] ' ` ` ` ` ` ` ' ' ] ` ` ` ` ` ` ` ` ] ] ' ` ` ` ` ' ' ' ] ] ] ] ] { [ ) r   ",
"  g <.&                                                                                         ",
"  g <.G x n n n m n n n n n m n n n n n m n m n m n n n m n n n m n n z k   g >.:.:.:.:.:.:.;.,.",
"  g <.T P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P I D Z   >.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L S C   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L P S C   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L S V   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L L S C   :.<.<.<.<.<.<.<.<.<.",
"  g <.Y K L L L L L L L L K L L L L L L L L L L L K L L L L L L L L L S C   :.<.<.<.<.<.<.<.<.<.",
"  h <.R I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I H Z   :.<.<.<.<.<.<.<.<.<.",
"  5 j e 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 q q q 9 8   ;.<.<.<.<.<.<.<.<.<.",
"6                                                                           ,.<.<.<.<.<.<.<.<.<."
]