table=[
"48 48 148 2 ",
"   c None",
".  c #44687D",
"X  c #49728A",
"o  c #527E97",
"O  c #318BBF",
"+  c #5285A2",
"@  c #5489A6",
"#  c #598EAB",
"$  c #4689B0",
"%  c #4B8CB2",
"&  c #5290B4",
"*  c #5E96B4",
"=  c #5F9BBB",
"-  c #629CBC",
";  c #358EC1",
":  c #388FC1",
">  c #3791C4",
",  c #3C92C4",
"<  c #3C96C9",
"1  c #3E99CC",
"2  c #4396C5",
"3  c #4997C4",
"4  c #449AC7",
"5  c #4B9AC7",
"6  c #4197C9",
"7  c #439BCC",
"8  c #4D9DCA",
"9  c #539DC7",
"0  c #529ECA",
"q  c #439ED1",
"w  c #489FD1",
"e  c #609FC1",
"r  c #4BA0CE",
"t  c #5EA1C5",
"y  c #55A1CD",
"u  c #5AA3CC",
"i  c #46A1D4",
"p  c #4CA3D3",
"a  c #44A6DB",
"s  c #4AA6D9",
"d  c #43A9DF",
"f  c #4DAADD",
"g  c #53A5D3",
"h  c #5AA6D1",
"j  c #53A8D6",
"k  c #5CAAD5",
"l  c #53A7D8",
"z  c #53ACDD",
"x  c #5CADDB",
"c  c #5DB0DE",
"v  c #61A0C2",
"b  c #6DABCD",
"n  c #63ABD5",
"m  c #61AEDA",
"M  c #6FB1D4",
"N  c #61B1DD",
"B  c #70B2D6",
"V  c #72B5DB",
"C  c #44ABE2",
"Z  c #4EADE1",
"A  c #4DAEE1",
"S  c #4FAEE1",
"D  c #4CADE2",
"F  c #4CAEE3",
"G  c #4FAFE3",
"H  c #4CACE0",
"J  c #48ADE4",
"K  c #49AEE4",
"L  c #4BAFE4",
"P  c #4DAFE4",
"I  c #4FAFE4",
"U  c #4CADE2",
"Y  c #50AFE1",
"T  c #50AFE2",
"R  c #57AFE0",
"E  c #53AFE1",
"W  c #58AFE0",
"Q  c #4EB0E3",
"!  c #4EB0E4",
"~  c #4DB0E4",
"^  c #51B0E2",
"/  c #53B1E3",
"(  c #55B0E1",
")  c #54B0E2",
"_  c #55B2E3",
"`  c #51B1E5",
"'  c #53B1E4",
"]  c #51B2E5",
"[  c #53B2E5",
"{  c #51B2E6",
"}  c #52B2E6",
"|  c #55B3E5",
" . c #57B3E5",
".. c #54B3E6",
"X. c #56B4E5",
"o. c #52B0E3",
"O. c #59B1E1",
"+. c #5AB1E0",
"@. c #59B2E1",
"#. c #5BB2E1",
"$. c #5AB1E2",
"%. c #58B2E3",
"&. c #5BB2E3",
"*. c #5AB2E3",
"=. c #5BB4E3",
"-. c #5CB5E3",
";. c #59B3E4",
":. c #5BB3E4",
">. c #5CB3E4",
",. c #59B4E5",
"<. c #5BB4E4",
"1. c #5BB4E5",
"2. c #5AB5E5",
"3. c #59B5E7",
"4. c #5BB5E7",
"5. c #5CB4E4",
"6. c #5DB5E4",
"7. c #5CB5E5",
"8. c #5DB6E5",
"9. c #5CB5E6",
"0. c #5DB5E6",
"q. c #5DB5E7",
"w. c #5DB6E7",
"e. c #5EB6E6",
"r. c #5EB6E7",
"t. c #5EB7E7",
"y. c #5DB4E3",
"u. c #5EB8E7",
"i. c #59B6E8",
"p. c #5BB6E8",
"a. c #5BB7E8",
"s. c #5BB7E9",
"d. c #5DB7E8",
"f. c #5DB7E9",
"g. c #5EB7E8",
"h. c #5BB9EA",
"j. c #5CB8E9",
"k. c #5EB8E8",
"l. c #5EB8E9",
"z. c #5FB8E9",
"x. c #5DB8EA",
"c. c #5CB9EA",
"v. c #5DB9EB",
"b. c #5EB9EA",
"n. c #5DBBEB",
"m. c #62B7E7",
"M. c #6EBEE8",
"N. c #74BCE4",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                              7 7                                               ",
"                                            1 C J 7                                             ",
"                                          7 d d C J 7                                           ",
"                                        r d d d C C J r                                         ",
"                                      8 d d C d C C C J r                                       ",
"                                    p d d d d C C C C J J r                                     ",
"                                  j U U U S d d d d d J J J g                                   ",
"                                j s H U S P ! P d d C J J J ~ g                                 ",
"                              j s H H U S P ] ] ] U d U J J J K j                               ",
"                            g s H s H U S S ^ ] ] ] U f d J J K L z                             ",
"                          g s a s H H H S S T ^ ] ] ] Q f U U ~ L L z                           ",
"                        g a a a s s s f f ^ ^ ^ ] ..] ] f f U U L S P x                         ",
"                      g i i i s s s s f f z ( ..3.h.h.h.i.Q Q U U L L ! c                       ",
"                    g q i i i s s s f S R 3.3.p.p.f.k.n.n...] ] ] S P P P W                     ",
"                  p q q q i i s s f z ;.;.>.>.0.0.f.k.k.n.p.....E ..] P P ! &.                  ",
"                8 1 7 q q i i i s z %.%.&.>.-.0.0.0.k.k.k.k.( ^ ......] ] P P &.                ",
"              8 1 1 q q q i q p z x z %.%.%.-.-.0.0.0.k.f.m.3.( T ( ..] ] P ! ! &.              ",
"            5 < 1 1 q q q p p z z x %.%.c %.&.&.-.0.0.0.k.f.0.( ^ ^ ^ ] ^ ] ! ! Q -.            ",
"          7 > < 1 1 7 7 q i p z z z z x c %.%.-.-.&.-.m.0.f.0.( R ^ ( ^ ^ ] ! S P ! 0.          ",
"        2 > > < < 1 7 7 7 w l z x z c N x %.c c &.m.m.-.0.m.0.( R R R T ^ ] ^ S S P ! 0.        ",
"      6 ; ; > , < 1 7 7 7 p l l z x N.N x c c %.c c &.-.-.M.m.( R z T R T T ^ S S P P P 0.      ",
"    2 ; ; ; > , < 2 4 7 q p l j x - . N x c x c c c -.m.c N.b =.z ( ( ( T z ^ T S S P L P 0.    ",
"    $ ; ; ; > , < 2 4 7 7 g j k -     N x x c c c c c c N N.  v c z z ^ z T ^ ^ S U S S ] u     ",
"      % O O > > < < 4 7 7 g k -       N x x c c c c c m.m.N.    v c z z z T z f f H S ^ t       ",
"        & > : > , < 4 4 7 h *         m x x c x N c c c c N.      v %.z z f f S f H T t         ",
"          % 2 > , 2 2 2 y #           N k x x x c N N c N N.        e c z z z f f T t           ",
"            & 2 , , 2 8 @             N x x N m x m c c N N.          - z z f z z t             ",
"              & 2 , 5 +               m x k k k m m N N x V             = x f z t               ",
"                & 5 +                 n k k m m x m c x x V               * c v                 ",
"                  X                   n k k n x n m x k k N.                o                   ",
"                                      n k k k n k k k k k V                                     ",
"                                      n h k k k k k k k k V                                     ",
"                                      n h h h k k k k k k V                                     ",
"                                      n u h h k h k h h h V                                     ",
"                                      u y y u u u h h h g V                                     ",
"                                      u y y y y u h g g g B                                     ",
"                                      u 8 0 y y y y y y g B                                     ",
"                                      u 9 0 0 0 y y y y y B                                     ",
"                                      u 5 5 5 0 8 r 8 0 r B                                     ",
"                                      9 5 5 5 9 8 8 8 8 8 B                                     ",
"                                      9 3 5 5 5 8 8 8 8 8 M                                     ",
"                                      u 9 9 9 y y u y u y B                                     ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]
