table = [
"48 48 57 1 ",
"  c None",
". c #3C3C3C",
"X c #403F40",
"o c #434343",
"O c gray29",
"+ c #535353",
"@ c #585757",
"# c #5B5B5B",
"$ c gray39",
"% c #676768",
"& c gray42",
"* c #706F6F",
"= c #6F6F70",
"- c gray45",
"; c #787777",
": c #7B7A7A",
"> c #807F7F",
", c #769455",
"< c #7E8F71",
"1 c #888F75",
"2 c #858484",
"3 c #888787",
"4 c #898F83",
"5 c #8C8B8B",
"6 c #949394",
"7 c #989797",
"8 c #979798",
"9 c #9C9B9B",
"0 c #A09F9F",
"q c #A19FA0",
"w c #A5A4A4",
"e c #A8A7A7",
"r c #A7A7A8",
"t c #A8A7A8",
"y c gray67",
"u c #B0AFAF",
"i c #AFAFB0",
"p c #B4B4B4",
"a c #B9B6B6",
"s c #B7B7B8",
"d c #BBBBBB",
"f c #BFBFC0",
"g c #C2C2C3",
"h c #C7C7C8",
"j c #CBCBCB",
"k c #CECED1",
"l c #D3D3D5",
"z c #D6D6D9",
"x c #DBDBDD",
"c c #DFDFE0",
"v c #E3E3E4",
"b c #E7E7E8",
"n c #ECECEC",
"m c #EFEFF0",
"M c #F3F3F4",
"N c #F7F7F8",
"B c gray98",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"         fkkkjjjjjjjjjjjjjjjjjhhhhhhhhp%        ",
"       -NBNNNNNNBBNBNNNNMMMMMMMMMMMMMmNk3       ",
"       vbBMmMMMMMMMMMMMMMMmmMnnnbbbbbvNmz       ",
"       bbBMMMMMMMMMNMMMMMMmMmMnnmmbbccMmn-      ",
"       vbBMMMmMMMMMMMMMMMMMnnnnnnbvcccMmn;      ",
"       vbBMMMMMMNMNMNMMMMmMMmnnnbvccccMmm:      ",
"      #vbBMmMMMMMNMNMMMMMnldvnnbvcccccMmm3      ",
"      $vbBmMmMMMMMNNMMMMbyydvbvvvvccccMmn6      ",
"      %vvBMMmMMMMMMMMMMmsffhbvvvvvccxxMmnw      ",
"      -vbBmMmmmMMMMMMMMbfghvbbvvvcccxxMMmp      ",
"      3vvBmmmMMMMMMMMmmvzcbbbvvvccvcxxMMnd      ",
"      8cvBmmmmmmMMcy99wsgprwrgvvvccxxxmMng      ",
"      wxvBmmmmmmnbwpsdfddgggdysvccccxzmMmj      ",
"      yxvBnmnmmmnfypssddffddsykcccccxxmMnl      ",
"      pxvBnnnnmnniippssddsdspjcccxxxxznMnx      ",
"      sxvBmbnbnbviyiipppsssppccccxxxxznMmv      ",
"      gxvNbbnnbvvpyyipippppppcccxxxxxznMmb      ",
"      hzcNbbbvvvvptyyyiiiiiirgccxxxxzznMnn      ",
"      hlvNbbvvvvvhtyttyyrryrr9gcxxxxzzbMnn      ",
"      jlcNbvcccvvxtttyyrrrrrrrrzxxzzzzbMnn      ",
"      jlcMvcccccccgrrrrrrrrrrrkcxzzzzzbMnn      ",
"      jjcMxcccccccxsyryrrrrrrfzzzzzzllvMnn      ",
"      jjcMxxxcxcxccxgisggsrrgzzzzzzlllvMMn3     ",
"      hjxmxxxxxxxxxxxxxxcczzzzzzzzllllcNnn-     ",
"     -hgxmzxxxxxxxxxxxxxxzzzzzzzlzllllxBnn-     ",
"     #gdcnzxzxxxxxxxxxzzzzzzzzzzllllkkxBnM:     ",
"     %ddcnzzzzxzzxzzxzzzzzzzzzzzllllkkxBnn2     ",
"     &sdcnzzzzzzzzzzzzzzzzzlllllllkkkkzBnn5     ",
"     -psvblzzlzzlzzzzlllzzllllllllkkjjzBmm6     ",
"     ;pdhjdggggggggggggfgdfffdddssssapsjzv9     ",
"     2fgappppppsaaaaapppppppppiiiyyyyyyuggw     ",
"     7jcnnbnnbnnbnnbnnnbbbnnbbbbbbbbbbbbblw     ",
"     thuuyuueeweywtywppppuuuuuiiuyyyyydfgla     ",
"     9paaaaa5:#32#>5$auyw99652:;=%#@+O7kkkt     ",
"     6aaaaaa5;+2>@:2#aytq9653>;=&$@+OX:kkkt     ",
"     7paaaaa5;+2>@:2#putq96531;-&$#+OX*kkly     ",
"     3aa<,ud5;+21@:2#sytq96532;-&$#OX.;kkl9     ",
"     Xpa41ua63&55&36=dpieww9653-#+Oooo0kkkO     ",
"      .20wwwweweeeettttttytytyyyyyyuyupy6X      ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
]