table=[
"48 48 40 1 ",
"  c None",
". c #3E3E3E",
"X c #3F3F3F",
"o c #42413D",
"O c #41403E",
"+ c #45433D",
"@ c #46443C",
"# c #4B473B",
"$ c #5E5536",
"% c #655A34",
"& c #816D2C",
"* c #826E2C",
"= c #86712B",
"- c #9A7F25",
"; c #BA931D",
": c #BA941C",
"> c #BB941C",
", c #BB951C",
"< c #BC951C",
"1 c #BD961C",
"2 c #AF8B20",
"3 c #C99E18",
"4 c #C99F18",
"5 c #CA9F18",
"6 c #CBA018",
"7 c #CCA018",
"8 c #DBAA14",
"9 c #EFB80E",
"0 c #F4B600",
"q c #F5B600",
"w c #F4B700",
"e c #F5B700",
"r c #FABD06",
"t c #FCBF08",
"y c #E2AE12",
"u c #E7B310",
"i c #FEC10A",
"p c #FEC20A",
"a c #FFC20A",
"s c #FFC20B",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"     000000000000000000                         ",
"    0000000000000000000                         ",
"    0000000000000000000000000000000000000000    ",
"    0000000000000000000000000000000000000000    ",
"   trrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrt   ",
"  iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii8;;;;;;;yiiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii-XXXXXXX2iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiu&&&$XXXXXXX%&&=9iiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiii:oXXXXXXXXXXX@4iiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiii:oXXXXXXXXX@4iiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiii:oXXXXXXX+4iiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiii<oXXXXX@4iiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiiii:oXXX@4iiiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiiiii<oX+6iiiiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiiiiii<#7iiiiiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiiiiiii9iiiiiiiiiiiiiiiiiiiiiiiiiiiii  ",
"  iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii  ",
"   iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii   ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
]
