table=[
"48 48 141 2 ",
"   c None",
".  c #276285",
"X  c #296587",
"o  c #296689",
"O  c #366B89",
"+  c #3D7EA4",
"@  c #4D6E80",
"#  c #427A99",
"$  c #3F80A5",
"%  c #3E83AA",
"&  c #2381B7",
"*  c #2485BB",
"=  c #2887BD",
"-  c #2688BE",
";  c #2C89BE",
":  c #318BBE",
">  c #4A87A7",
",  c #4185AC",
"<  c #4589AF",
"1  c #4D8AAB",
"2  c #528DAE",
"3  c #4A8DB3",
"4  c #4292BF",
"5  c #4F92B9",
"6  c #5692B2",
"7  c #5A95B7",
"8  c #5D98B8",
"9  c #2689C0",
"0  c #2C8CC2",
"q  c #328EC2",
"w  c #3491C5",
"e  c #3A93C6",
"r  c #3694C9",
"t  c #3B96C9",
"y  c #3E99CB",
"u  c #4694C0",
"i  c #4996C1",
"p  c #4D99C4",
"a  c #4197C8",
"s  c #449CCD",
"d  c #499ECE",
"f  c #529DC6",
"g  c #5A9CC2",
"h  c #479FD1",
"j  c #499FD0",
"k  c #4EA0CC",
"l  c #51A2CE",
"z  c #5CA2C9",
"x  c #46A1D4",
"c  c #4CA3D4",
"v  c #45A6DB",
"b  c #4AA7DA",
"n  c #4DA6D8",
"m  c #4FA7D9",
"M  c #46A8DD",
"N  c #47A9DF",
"B  c #47AADF",
"V  c #4FA8D9",
"C  c #49A9DD",
"Z  c #4BA9DD",
"A  c #4AAADD",
"S  c #48A9DE",
"D  c #49AADE",
"F  c #4AABDE",
"G  c #4FABDD",
"H  c #4DABDE",
"J  c #4EACDF",
"K  c #52A5D1",
"L  c #53A6D3",
"P  c #54A5D0",
"I  c #55A7D2",
"U  c #51A7D7",
"Y  c #51A6D5",
"T  c #57AAD6",
"R  c #54A8D7",
"E  c #58AAD6",
"W  c #51A9D9",
"Q  c #51A9DA",
"!  c #53ABDB",
"~  c #54ABDB",
"^  c #53ACDB",
"/  c #55ACDB",
"(  c #57ACDB",
")  c #50ABDD",
"_  c #50ACDE",
"`  c #53ADDE",
"'  c #55ADDC",
"]  c #57ADDC",
"[  c #55AEDF",
"{  c #54ACDB",
"}  c #58ADDC",
"|  c #59AEDD",
" . c #5AAEDC",
".. c #5CAFDD",
"X. c #5CAFDE",
"o. c #5AADDB",
"O. c #59B0DE",
"+. c #5DB0DF",
"@. c #5EB2DF",
"#. c #5DB1DE",
"$. c #6FA7C4",
"%. c #6FA8C7",
"&. c #65A7CB",
"*. c #6BA8CA",
"=. c #70A8C6",
"-. c #70ABCC",
";. c #61B1DD",
":. c #77B7DA",
">. c #78B9DC",
",. c #47ABE1",
"<. c #48ABE1",
"1. c #4AABE0",
"2. c #4CACE0",
"3. c #4CADE0",
"4. c #4CADE2",
"5. c #52AFE1",
"6. c #4FB0E4",
"7. c #54B1E4",
"8. c #58B0E0",
"9. c #5EB1E0",
"0. c #5EB2E0",
"q. c #5FB3E1",
"w. c #5EB3E2",
"e. c #5BB4E4",
"r. c #60B3E1",
"t. c #60B4E3",
"y. c #63B4E2",
"u. c #66B5E0",
"i. c #63B5E3",
"p. c #69B7E2",
"a. c #65B9E6",
"s. c #6ABAE6",
"d. c #65BBE9",
"f. c #6BBEEA",
"g. c #75BEE6",
"h. c #7DBEE1",
"j. c #70BEE9",
"k. c #6CC0ED",
"l. c #7FC2E6",
"z. c #71C0EB",
"x. c #7EC5EB",
"                                                                                                ",
"                                                                                                ",
"                                    X o o o X X o X X . .                                       ",
"                                    0 - = - * * * & & + *                                       ",
"                                    0 9 - - * * * & * + *                                       ",
"                                    0 9 - - - - * * * + *                                       ",
"                                    w 9 9 9 = = * * * * =                                       ",
"                                    w 0 9 0 9 9 9 9 = - ;                                       ",
"                                    r 0 0 0 0 0 9 9 9 9 0                                       ",
"                                    r w w w 0 0 9 9 0 0 q                                       ",
"                                    y r w w w 0 0 0 0 0 q                                       ",
"                                    y r r r w q 0 0 0 0 e                                       ",
"                                    h r r r r r r w q q e                                       ",
"                                    b y y t t e e e w q t                                       ",
"                                    ` x x x h t t e e r a                                       ",
"                  #                 ` b x x x x s t t t a                   O                   ",
"                d b 1               ] n n n x x x k y y s                 , : +                 ",
"              K v v G >             } b n n n c n n k y s               , : : : +               ",
"            K v v Z C ` 2           X.b V V V V n n c c d             < e : : : : +             ",
"          I v v Z Z Z Z ] 2         @.Q Q Q Q Q U U U U I           3 e w q q : : : +           ",
"        L ,.M Z Z F F H ) 5.6       q.^ ^ ^ ] ] } } } } ;.        5 y e e e q : : ; : +         ",
"      R ,.,.,.1.3.3.H H 2.5.8.7     y.] O.0.t.q.0.0.@.X.u.      8 s t e e e e q q : ; : ,       ",
"    E 3.,.3.3.3.3.3.3.` 5.5.5.e.8   s.t.a.t.y.y.y.0.0.@.p.    g c k s a e e e q q : : ; : +     ",
"    e.<.<.3.3.3.3.3.5.5.5.5.8.5.0.-.z.a.t.a.t.t.y.y.r.0.p.@ &.Y c k d s a e e e w q q ; ; 4     ",
"      e.6.6.<.6.6.6.6.6.7.7.7.7.t.f.z.a.a.a.a.i.y.y.y.y.s.g.@.K c c d s s a e e e w q q u       ",
"        e.6.6.6.7.6.7.7.7.7.7.d.d.d.d.a.a.a.a.i.a.t.t.y.p.y.@.Y K c j d s s t e e w w i         ",
"          e.6.6.6.7.7.7.e.7.e.d.d.d.d.a.s.s.s.s.a.a.u.u.y.r.@.R K c c d h s s t e e p           ",
"            e.6.7.7.7.7.e.e.d.d.d.d.f.f.d.s.s.s.s.s.a.u.u.r.r.E K c c c j s s y e f             ",
"              d.7.7.7.7.7.7.d.d.f.f.f.f.f.f.f.s.s.s.p.s.i.u.r.( L Y n c c s s s f               ",
"                f.7.7.d.e.d.k.f.f.f.f.f.j.f.f.j.f.s.s.s.s.u.y.o.L Y Y c c c s z                 ",
"                  f.7.7.d.d.f.f.f.f.f.f.j.f.j.j.f.s.s.s.s.i.u.E ( Y K c c d z                   ",
"                    f.d.7.d.f.f.f.f.f.f.j.z.j.j.j.j.f.s.s.i.u.( ( L Y n c z                     ",
"                      z.e.d.k.k.k.k.k.k.k.z.z.z.z.z.j.s.s.a.;.O.T U U L &.                      ",
"                        z.k.k.k.k.k.k.k.k.z.z.z.z.z.j.s.s.p.@.O.T ^ T &.                        ",
"                          z.k.k.k.k.k.k.z.z.z.z.z.j.k.s.s.;.O.O.( O.*.                          ",
"                            z.k.k.k.k.k.k.z.z.z.z.z.j.s.a.@.#.O.O.*.                            ",
"                              x.k.k.k.k.k.k.z.k.z.s.d.s.i.@.#.@.*.                              ",
"                                l.k.k.k.k.k.k.k.k.s.a.i.i.@.i.%.                                ",
"                                  l.k.k.k.k.f.d.s.a.a.y.w.a.%.                                  ",
"                                    l.k.d.d.d.a.a.a.i.y.a.=.                                    ",
"                                      l.d.d.d.d.a.a.a.d.*.                                      ",
"                                        >.k.d.d.a.a.d.=.                                        ",
"                                          >.d.d.e.d.-.                                          ",
"                                            :.d.d.%.                                            ",
"                                              :.%.                                              ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]
