table=[
"48 48 139 2 ",
"   c None",
".  c #36647F",
"X  c #386178",
"o  c #2C6584",
"O  c #376884",
"+  c #3F6A84",
"@  c #3D6D88",
"#  c #38708E",
"$  c #2F6E91",
"%  c #306E90",
"&  c #3B7392",
"*  c #3B7698",
"=  c #35799F",
"-  c #3D7A9B",
";  c #55798C",
":  c #437693",
">  c #4C7A93",
",  c #5B7F91",
"<  c #3880A8",
"1  c #3C8BB6",
"2  c #308BBF",
"3  c #4D809D",
"4  c #538098",
"5  c #5D879D",
"6  c #4382A3",
"7  c #4586A9",
"8  c #5E8AA2",
"9  c #578EAC",
"0  c #5D8FAA",
"q  c #478EB5",
"w  c #4E92B7",
"e  c #4292BE",
"r  c #5D96B6",
"t  c #658EA3",
"y  c #6296B2",
"u  c #629DBE",
"i  c #338DC1",
"p  c #3691C4",
"a  c #3A93C5",
"s  c #3197CF",
"d  c #3D96C8",
"f  c #3C99CC",
"g  c #3297D0",
"h  c #359BD3",
"j  c #399DD4",
"k  c #379FD8",
"l  c #3DA1D7",
"z  c #3BA2DA",
"x  c #4396C4",
"c  c #4996C3",
"v  c #439BCC",
"b  c #4A9DCC",
"n  c #559DC4",
"m  c #529FCB",
"M  c #489FD0",
"N  c #5DA1C7",
"B  c #58A0C9",
"V  c #4CA2D1",
"C  c #43A5DB",
"Z  c #4AA6D9",
"A  c #44A8DF",
"S  c #4BA9DC",
"D  c #52A5D4",
"F  c #55A9D6",
"G  c #5BAAD5",
"H  c #54AADA",
"J  c #5BADDA",
"K  c #5EB0DC",
"L  c #61A1C4",
"P  c #69A2C0",
"I  c #61A6CC",
"U  c #70ABCB",
"Y  c #60AAD4",
"T  c #62B2DE",
"R  c #6CB6DE",
"E  c #76B3D6",
"W  c #7ABBDD",
"Q  c #43A9E0",
"!  c #44A9E0",
"~  c #44AAE1",
"^  c #47AAE0",
"/  c #45ABE2",
"(  c #46ACE3",
")  c #46ACE4",
"_  c #48ABE1",
"`  c #49ACE2",
"'  c #4BAEE3",
"]  c #4DACE0",
"[  c #4FAEE3",
"{  c #49AEE4",
"}  c #49AFE6",
"|  c #4CAFE5",
" . c #50ADE0",
".. c #4EB2E7",
"X. c #4FB2E9",
"o. c #53B0E3",
"O. c #56B0E3",
"+. c #50B2E5",
"@. c #51B2E7",
"#. c #52B3E7",
"$. c #55B3E4",
"%. c #56B2E4",
"&. c #55B3E7",
"*. c #57B3E6",
"=. c #58B1E1",
"-. c #59B2E3",
";. c #5BB3E3",
":. c #5BB4E3",
">. c #59B3E4",
",. c #58B4E5",
"<. c #5BB4E5",
"1. c #58B4E7",
"2. c #5AB4E6",
"3. c #5DB5E5",
"4. c #50B3E8",
"5. c #52B3E8",
"6. c #53B5E9",
"7. c #51B5EA",
"8. c #55B4E9",
"9. c #57B5E9",
"0. c #55B6E9",
"q. c #54B5EA",
"w. c #5BB6E8",
"e. c #5EB8E9",
"r. c #64B7E3",
"t. c #63B6E3",
"y. c #68B7E1",
"u. c #65B9E6",
"i. c #65B9E6",
"p. c #6BBAE6",
"a. c #67BCE9",
"s. c #60B8E8",
"d. c #69BCEA",
"f. c #74BCE3",
"g. c #7ABEE3",
"h. c #7EC1E4",
"j. c #75C0E9",
"k. c #7CC3EA",
"l. c #80C4E8",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                        $ o                     ",
"                                                                      o h h %                   ",
"                                                                      h g g h =                 ",
"                                                                    j g g g h h <               ",
"                                                                  f g g g h h h z 1             ",
"                                                                d g g g g h h z k z x           ",
"                                                              v l h g g h g k k k z z d         ",
"                                                            x l z z l h k h h k z z z z V       ",
"                                                          e l l C z z z k k k z z z z A         ",
"                                                        q C l l z z A z z k z z z z A           ",
"                                                      7 C l l z z C Q Q Q Q z z z Q #           ",
"                                                    : Z C C C C A z Q Q Q Q / z z -             ",
"                                                  : Z C C C C C C C Q Q Q ) ) ` 6               ",
"                                                : D Z Z Z A C A ^ Q ^ ^ ) ) ..w                 ",
"                - x                             H Z Z Z Z S A S ^ ^ ` { ....n                   ",
"              & p p b                         J Z Z Z S S S ] [ ..5.X.X.X.G                     ",
"            O a i p d M +                   Y Z Z S S S ] o.$.$.$.5.6.6.K                       ",
"          O a i i d d v V >               Y H S S H H O.&.&.&.6.6.6.0.r.                        ",
"          x 2 i p d v v v V >           I H H H H =.=.,.,.,.1.1.0.0.u.                          ",
"        x i i i a v v v v b D 9       L H H H H :.:.:.3.,.,.1.,.0.a.                            ",
"      c i i i p d v v v M M D F r   u J H H J ;.3.3.3.3.w.1.1.1.j.                              ",
"      @ x i i a v v v b M M D D G R J H H J 3.3.3.3.3.3.w.e.1.d.>                               ",
"        X b a a v v M M V V D D F H J J J t.t.3.3.t.e.e.s.e.d.4                                 ",
"            m d v b M M V D D F H J J J t.r.t.t.i.t.i.e.s.d.0                                   ",
"              n v M M V D D F F J J J t.r.r.r.r.t.t.i.e.d.y                                     ",
"                N V M D D F F J J J T t.y.i.u.u.s.i.i.d.P                                       ",
"                  L D D D F J J J T T p.p.p.p.i.i.i.j.U                                         ",
"                    L J F F J J T T R p.p.p.p.p.i.p.E                                           ",
"                      y Y J J J T T p.p.p.p.p.p.d.W                                             ",
"                        y T J J T T p.f.p.p.p.p.h.                                              ",
"                          8 y.T T T p.p.p.p.p.l.                                                ",
"                            5 f.T T p.p.p.p.k.                                                  ",
"                              ; g.t.p.p.p.k.                                                    ",
"                                  g.p.i.k.4                                                     ",
"                                    h.j.t                                                       ",
"                                      t                                                         ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]
