table = [
"48 48 163 2 ",
"   c None",
".  c #013467",
"X  c #023769",
"o  c #053B6D",
"O  c #083D6F",
"+  c #0A3F71",
"@  c #064173",
"#  c #0C4273",
"$  c #0C4A7C",
"%  c #124575",
"&  c #134A7B",
"*  c #1A4D7B",
"=  c #15507F",
"-  c #145281",
";  c #1B5B89",
":  c #205584",
">  c #265A87",
",  c #2D5A85",
"<  c #225C8A",
"1  c #2A5D89",
"2  c #11679F",
"3  c #11689F",
"4  c #23618F",
"5  c #34648F",
"6  c #3A668E",
"7  c #246391",
"8  c #2C6591",
"9  c #2D6D99",
"0  c #356A96",
"q  c #3B6F99",
"w  c #2E719D",
"e  c #34749E",
"r  c #3C729B",
"t  c #136BA2",
"y  c #1B6DA3",
"u  c #1270A7",
"i  c #1F70A4",
"p  c #1374AA",
"a  c #1479AF",
"s  c #147CB2",
"d  c #187EB3",
"f  c #2372A6",
"g  c #2B74A5",
"h  c #2576A9",
"j  c #2A77A9",
"k  c #2778AB",
"l  c #2A7AAC",
"z  c #3C7AA2",
"x  c #357DAC",
"c  c #397EAC",
"v  c #247DB0",
"b  c #2D7FB0",
"n  c #427097",
"m  c #43729A",
"M  c #48789F",
"N  c #437AA3",
"B  c #497DA5",
"V  c #447EA8",
"C  c #1581B6",
"Z  c #1685BA",
"A  c #1E87BA",
"S  c #178ABE",
"D  c #3981AF",
"F  c #2D83B3",
"G  c #3385B5",
"H  c #3D83B0",
"J  c #358BBA",
"K  c #3A8FBC",
"L  c #3A91BE",
"P  c #4383AB",
"I  c #4B83AA",
"U  c #568BAE",
"Y  c #598BAE",
"T  c #4184B0",
"R  c #4489B3",
"E  c #4A8DB5",
"W  c #438EB9",
"Q  c #558EB5",
"!  c #588EB2",
"~  c #4491B9",
"^  c #4994BC",
"/  c #5D91B4",
"(  c #5093BB",
")  c #5C95BB",
"_  c #609DBE",
"`  c #178CC1",
"'  c #198FC2",
"]  c #1992C5",
"[  c #1996C9",
"{  c #1B9BCD",
"}  c #1B9ED0",
"|  c #2194C6",
" . c #229BCC",
".. c #2D9DCC",
"X. c #3094C3",
"o. c #3D96C2",
"O. c #3E9AC5",
"+. c #319BC9",
"@. c #1CA3D5",
"#. c #1DA7D8",
"$. c #1DABDC",
"%. c #22A2D2",
"&. c #32A5D3",
"*. c #1EAFE0",
"=. c #1FB3E3",
"-. c #20B7E6",
";. c #20B8E7",
":. c #20BAE9",
">. c #3EBDE7",
",. c #4597C2",
"<. c #429BC6",
"1. c #4A99C1",
"2. c #479FC9",
"3. c #5D9EC3",
"4. c #45A1CB",
"5. c #4AA4CD",
"6. c #4FA8CF",
"7. c #50A0C6",
"8. c #52A7CC",
"9. c #49A7D0",
"0. c #42ACD5",
"q. c #4DABD2",
"w. c #53ADD3",
"e. c #5BABD0",
"r. c #4DB5DC",
"t. c #54B1D7",
"y. c #55B4DA",
"u. c #5AB5DA",
"i. c #52B8DE",
"p. c #5BB9DD",
"a. c #63A9CC",
"s. c #68A8CA",
"d. c #71B0CF",
"f. c #66AFD2",
"g. c #63B3D5",
"h. c #67B7D9",
"j. c #64BADC",
"k. c #6ABDDD",
"l. c #75B4D2",
"z. c #72BCDC",
"x. c #7ABBD9",
"c. c #41BCE5",
"v. c #4CBDE4",
"b. c #54BBE1",
"n. c #5ABEE2",
"m. c #61BEE1",
"M. c #73C0DF",
"N. c #7EC0DD",
"B. c #65C2E4",
"V. c #6CC3E3",
"C. c #67C7E8",
"Z. c #6CC9E9",
"A. c #73C4E3",
"S. c #7AC7E4",
"D. c #7CC5E2",
"F. c #74C9E7",
"G. c #79C8E6",
"H. c #71CAE9",
"J. c #75CAE8",
"K. c #81C0DB",
"L. c #82C3DF",
"P. c #81C6E2",
"I. c #86C6E1",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                  o                                                             ",
"                                % ,                                                             ",
"                              # _ Y                                                             ",
"                            % U l.Y                                                             ",
"                          # B x.z.U                                                             ",
"                        O N N.z.z.!                                                             ",
"                        r L.z.z.z.!                                                             ",
"                      8 L.M.M.k.M._ % & & & & & % + . X #                                       ",
"                    8 L.D.A.A.A.V.S.A.k.k.k.h.h.g.f.f.a.3.I q * O                               ",
"                  < K.D.D.A.A.A.V.V.B.j.j.p.u.w.w.6.5.2.<.,.1.3./ 1 O                           ",
"                - K.P.D.S.F.A.V.V.V.V.B.m.p.u.t.w.6.5.2.<.,.K J G ( ! %                         ",
"              = x.I.D.S.S.F.F.F.Z.C.B.B.n.n.p.t.w.q.5.2.<.,.K J G b x ) :                       ",
"            & l.I.P.S.S.J.J.H.H.Z.Z.C.B.n.n.p.t.t.q.9.4.<.O.K J G b l j ) &                     ",
"          @ d.I.P.P.S.C.n.v.v.>.>.>.c.c.v.b.n.t.t.q.9.4.<.O.o.J G b l h j Q o                   ",
"        @ s.L.h.q.&.%.@.$.=.=.=.;.;.=.=.$.#.%.&.&.q.9.4.O.o.K J G b l h f D 0                   ",
"      . w e.| ] [ } @.#.#.=.=.=.:.=.=.=.*.#.#.} {  .+.2.O.o.o.J G b k h f f Q X                 ",
"        O R ..] [ } @.@.$.=.=.=.:.:.=.=.$.#.@.} { [ ' ' X.o.X.J G b k f i i R -                 ",
"          o ~ ..[ } @.@.#.=.=.=.;.;.=.=.$.#.@.} { [ ' ` Z A J J F b k f f y h q                 ",
"            @ ^ ..{ } @.#.$.$.=.=.=.=.$.$.#.} } [ [ ` ` Z C d F F b j f i y y B o               ",
"              @ 7. .} @.#.#.$.=.=.=.$.$.#.@.} { [ ' ` ` Z s s a v l j f i y y B o               ",
"                @ 8.%.{ @.@.#.$.$.$.#.#.@.@.{ { [ ' ` S C C s p p i h f y y t I O               ",
"                  $ 8.%.@.@.@.#.#.#.#.@.@.} { [ [ ' ` Z C s s p p t i f i y t B O               ",
"                    & w. .@.@.@.@.r.i.r.r.0.&. .' ` S C s s a p t t 2 y y y t N                 ",
"                      - w. .{ { %.~ @ $ & - 4 z E 1.O.A s s p p t 3 2 2 y y t m                 ",
"                        ; q.{ { } T             # @ * P K s p u t 2 2 2 2 t j ,                 ",
"                          4 q.[ [ P                   o 1 W p t 2 2 2 2 2 t T %                 ",
"                          O 7 9.| P                       > G t 2 2 2 2 2 2 I +                 ",
"                            O 9 5.P                       o P t 2 2 2 2 2 i 6                   ",
"                              o e I                         5 f t 2 2 2 2 z %                   ",
"                                o &                         * x 2 2 2 2 3 m                     ",
"                                  X                         & D 2 2 2 2 x *                     ",
"                                                            * c 2 2 2 t m                       ",
"                                                            > j 2 2 2 V %                       ",
"                                                            q y 2 2 g ,                         ",
"                                                          + N t 2 y n                           ",
"                                                          . E 2 2 m                             ",
"                                                          & P 3 B %                             ",
"                                                          r f B %                               ",
"                                                        o ! m %                                 ",
"                                                        + 6                                     ",
"                                                        .                                       ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]