table=[
"48 48 161 2 ",
"   c None",
".  c #255A79",
"X  c #2A5E7C",
"o  c #225E82",
"O  c #266386",
"+  c #2A6689",
"@  c #2F6989",
"#  c #336783",
"$  c #376883",
"%  c #3B6B85",
"&  c #356C8B",
"*  c #3A6F8C",
"=  c #2D6D90",
"-  c #316E91",
";  c #23729F",
":  c #397495",
">  c #3E7898",
",  c #1C79AF",
"<  c #1C7BB2",
"1  c #2573A1",
"2  c #2975A2",
"3  c #237FB4",
"4  c #406D86",
"5  c #4D7287",
"6  c #42718B",
"7  c #4E7488",
"8  c #53778A",
"9  c #57798C",
"0  c #597C8E",
"q  c #467997",
"w  c #497C98",
"e  c #3082AF",
"r  c #2281B7",
"t  c #2584BB",
"y  c #2986BD",
"u  c #2988BE",
"i  c #3485B3",
"p  c #3788B5",
"a  c #328CBF",
"s  c #3B8DB9",
"d  c #3F90BC",
"f  c #4F819D",
"g  c #50839E",
"h  c #5A859B",
"j  c #60869C",
"k  c #5185A1",
"l  c #5388A4",
"z  c #4F8DB0",
"x  c #538FB2",
"c  c #4293BE",
"v  c #5693B4",
"b  c #5A95B6",
"n  c #5E9CBC",
"m  c #649EBD",
"M  c #65A0BF",
"N  c #69A2BF",
"B  c #2D8BC1",
"V  c #318EC3",
"C  c #2E92CA",
"Z  c #3491C5",
"A  c #3B94C7",
"S  c #3295CC",
"D  c #3A96CA",
"F  c #3599CF",
"G  c #3D99CD",
"H  c #3297D0",
"J  c #359BD3",
"K  c #3B9DD4",
"L  c #379FD8",
"P  c #389FD8",
"I  c #3DA0D5",
"U  c #3CA1D9",
"Y  c #409CCF",
"T  c #429CCD",
"R  c #439CCE",
"E  c #4A9ECD",
"W  c #419DD1",
"Q  c #439DD0",
"!  c #419ED2",
"~  c #429ED2",
"^  c #449FD1",
"/  c #449ED1",
"(  c #47A1D3",
")  c #42A0D4",
"_  c #43A2D5",
"`  c #42A1D6",
"'  c #45A0D4",
"]  c #47A3D6",
"[  c #46A1D3",
"{  c #48A2D5",
"}  c #4BA3D5",
"|  c #4DA6D7",
" . c #4EA7D7",
".. c #4CA3D4",
"X. c #40A3D9",
"o. c #43A5DB",
"O. c #43A6DB",
"+. c #46A4D8",
"@. c #44A5DA",
"#. c #44A6DB",
"$. c #46A7DB",
"%. c #46A7DC",
"&. c #49A5D8",
"*. c #49A6DA",
"=. c #4DA6D8",
"-. c #4EA7D9",
";. c #4DA7DA",
":. c #4CA6D8",
">. c #4AA8DA",
",. c #4EA8DB",
"<. c #49A9DD",
"1. c #4BAADD",
"2. c #4EA9DC",
"3. c #4FAADD",
"4. c #4FABDE",
"5. c #4FACDF",
"6. c #4EAADB",
"7. c #50A5D4",
"8. c #51A8D7",
"9. c #50A7D9",
"0. c #50A9D9",
"q. c #51A9DB",
"w. c #52AADB",
"e. c #51AADD",
"r. c #53ABDD",
"t. c #51ACDD",
"y. c #51ADDF",
"u. c #54ACDE",
"i. c #54AEDE",
"p. c #54AADA",
"a. c #5AAEDD",
"s. c #5DB1DF",
"d. c #64A1C0",
"f. c #65B4DF",
"g. c #51ADE0",
"h. c #51AEE0",
"j. c #54AFE0",
"k. c #54AFE2",
"l. c #57AFE0",
"z. c #53B0E1",
"x. c #56B2E4",
"c. c #5CB4E4",
"v. c #5FB8E7",
"b. c #55B6EA",
"n. c #5AB6E9",
"m. c #55B9EE",
"M. c #5BBAEC",
"N. c #5DBEF0",
"B. c #62B5E3",
"V. c #6BB7E1",
"C. c #65B8E6",
"Z. c #69BAE5",
"A. c #63BBE9",
"S. c #6ABDEA",
"D. c #71BBE4",
"F. c #61BFF1",
"G. c #77C0E7",
"H. c #73C3ED",
"J. c #7CC4EB",
"K. c #64C0F1",
"L. c #6FC4F1",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                            ; o                                 = e                             ",
"                          ; < < O                             = C C e                           ",
"                        1 < , < r O                         = C C C C p                         ",
"                      1 < < < < < r O                     @ C C C C C H p                       ",
"                    1 < < < < < r r t +                 = C B C C C C C J s                     ",
"                  2 , , < < < r r t t B @             = C C C C H H H H H J s                   ",
"                2 , < < < < r t t u B B Z &         - S C C C C C H H H H J L d                 ",
"              2 , , < < < r t t u u B C C D &     : D C C C C H H H H H J L U U c               ",
"              . 3 < < < r t t t u u V C Z D G * > ) F S S F F F H H J J J L U X.#               ",
"                . 3 < < t t u u V V Z Z D D D ~ ^ K K ! J G H H J J J J L U X.#                 ",
"                  X y t t u B B Z Z Z D D D G K ~ ~ ` ` ] J K K K K I L U X.$                   ",
"                    X a u u V V Z Z D D G G T ~ ^ ] &.&.>.+.) K U K U U @.$                     ",
"                      # Z a V V Z D D D T ~ { -.-.-.2.2.y.y.@.@.@.X.U 2.$                       ",
"                        # D Z Z D D G T ( | -.0.0.w.y.y.y.y.2.%.@.%.y.%                         ",
"                          $ T A D G T ..| 9.0.0.u.u.i.j.j.z.z.<.<.s.%                           ",
"                            % E G T .. .0.0.p.i.i.i.a.z.z.z.x.5.x.4                             ",
"                              6 7.E 8.8.0.p.a.a.a.x.x.x.c.c.n.B.6                               ",
"                              w 7.8.8.p.p.p.i.s.c.s.c.c.c.n.n.B.g                               ",
"                            q ....8.p.p.a.a.s.s.s.c.c.c.c.v.c.n.c.w                             ",
"                          q ..E 8.8.p.a.s.s.s.s.B.B.B.B.B.c.v.n.z.c.k                           ",
"                        w ..E E 8.p.p.a.s.s.f.B.B.B.B.B.A.A.A.n.x.x.v.f                         ",
"                      q E T E ..p.p.a.f.s.f.B.B.C.C.C.C.A.A.A.n.x.x.x.v.k                       ",
"                    q E G T E ..p.a.a.s.f.B.B.Z.Z.Z.A.Z.A.A.A.n.n.x.b.b.A.g                     ",
"                  q E G T E ....p.a.a.f.B.B.Z.Z.Z.Z.S.A.S.A.c.c.n.b.b.b.m.M.l                   ",
"                q E D G T ^ E 8.p.a.s.B.B.Z.Z.J.J.H.S.S.S.A.v.v.n.n.n.b.b.m.A.k                 ",
"              q T D D G E ^ ..| 8.s.f.B.B.Z.J.0 j J.S.H.A.A.A.v.n.n.b.m.m.m.m.N.k               ",
"              x T D G G ~ ( ..| 8.a.s.B.B.J.0     j J.C.A.A.A.v.M.n.M.M.m.m.m.N.d.              ",
"                x T D T T ..{ | 8.p.a.B.G.9         h H.A.A.A.M.v.M.M.b.m.m.N.d.                ",
"                  v E ~ ~ ..| | 8.p.a.D.8             h H.A.A.M.M.m.m.N.m.N.d.                  ",
"                    b ..^ { | | 0.p.V.8                 h H.A.M.M.M.N.N.F.m                     ",
"                      n | ] ..-.0.Z.7                     h H.M.M.N.N.F.d.                      ",
"                        n 0.&.,.B.5                         h H.M.N.F.d.                        ",
"                          m p.f.5                             h H.F.d.                          ",
"                            m 5                                 h d.                            ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]