table=[
"48 48 121 2 ",
"   c None",
".  c #20375A",
"X  c #223A5D",
"o  c #233C61",
"O  c #305389",
"+  c #375A8F",
"@  c #2F5999",
"#  c #345E9D",
"$  c #37609F",
"%  c #3561A4",
"&  c #3C65A1",
"*  c #3F69A7",
"=  c #3564AA",
"-  c #3C69AC",
";  c #3567B1",
":  c #3768B0",
">  c #3B6BB3",
",  c #3B6FBD",
"<  c #3E71BD",
"1  c #426396",
"2  c #4067A2",
"3  c #4A6FA5",
"4  c #436CA8",
"5  c #4A72AE",
"6  c #597AAB",
"7  c #406DB0",
"8  c #4371B6",
"9  c #4F77B3",
"0  c #4172BC",
"q  c #4F7BBC",
"w  c #577CB2",
"e  c #3D73C4",
"r  c #3B74C9",
"t  c #4276C3",
"y  c #4D7DC6",
"u  c #4077CA",
"i  c #437ACB",
"p  c #497ECD",
"a  c #507EC3",
"s  c #6687B6",
"d  c #6A89B7",
"f  c #728FBA",
"g  c #7995BE",
"h  c #4D81CE",
"j  c #5281C6",
"k  c #5C85C3",
"l  c #5184CF",
"z  c #5986C9",
"x  c #5D89CB",
"c  c #5385D0",
"v  c #5788D1",
"b  c #5B8BD2",
"n  c #628DCC",
"m  c #618ED3",
"M  c #6592D3",
"N  c #779ED9",
"B  c #7EA3DB",
"V  c #849FC6",
"C  c #86A1C7",
"Z  c #8BA3C9",
"A  c #90A7CA",
"S  c #9DB0CD",
"D  c #87AADD",
"F  c #8DAEDF",
"G  c #A0B3CF",
"H  c #A3B7D4",
"J  c #93B2E2",
"K  c #A3BEE5",
"L  c #B2C3DE",
"P  c #B8C6DB",
"I  c #BBC9DD",
"U  c #A9C2E7",
"Y  c #ACC4E8",
"T  c #B3C7E3",
"R  c #BECEE6",
"E  c #BFD2ED",
"W  c #C2CEE1",
"Q  c #C7D2E3",
"!  c #C1D3EE",
"~  c #C0D2ED",
"^  c #C2D4EE",
"/  c #C4D5EE",
"(  c #C2D2E9",
")  c #D3E0F2",
"_  c #D5E1F3",
"`  c #D7E3F4",
"'  c #D9E4F3",
"]  c #D9E4F4",
"[  c #DDE7F5",
"{  c #DEE7F5",
"}  c #E1EAF6",
"|  c #E3EBF7",
" . c #E4EBF7",
".. c #E5ECF5",
"X. c #E6ECF5",
"o. c #E5ECF7",
"O. c #E8EFF7",
"+. c #E5EDF8",
"@. c #E7EEF8",
"#. c #E9EFF8",
"$. c #E9F0F8",
"%. c #E9F0F9",
"&. c #EDF2F9",
"*. c #EDF2FA",
"=. c #F1F5FA",
"-. c #F1F5FB",
";. c #F3F6FB",
":. c #F5F8FC",
">. c #F6F8FC",
",. c #F9FBFC",
"<. c #F9FAFD",
"1. c #F9FBFD",
"2. c #FAFBFC",
"3. c #FAFBFD",
"4. c #FAFCFD",
"5. c #FBFCFD",
"6. c #FDFDFE",
"7. c #FDFEFE",
"8. c #FEFEFE",
"9. c #FEFEFF",
"0. c white",
"                                                                                                ",
"                            M m m b b v v v v v v v v v b b b m m m                             ",
"                      m b v v v c c v c v c v v v v c v c c v c v v b b m                       ",
"                  m b v c c c c v v c c c c c c c c c c v v c c c c c c c v m                   ",
"                m c l c l l l c l l v l l v l z v l l c c l v l c l l v c c l b                 ",
"              v l c l v l l l c l l c l l c l l c l l c l l c l c l l c c z l l b               ",
"            v c v c c c c c c c c c c c c c c c c c c c c c c c c c c c c c l l c b             ",
"          x l l p l l l l l l l l l l l l l l l l l l l l l l l l c p l c c l l l l x           ",
"          v l p l l l p l l l l l c v p l l l l l l l p l l l p l l h l l h l l l l c           ",
"        9 l l l l l l l l l p l p c p c p l l l l l l l l l l l l l l l l l l l l l l 9         ",
"        v l p l p l p l l h l l c p p z l p l p l l l l p c p l l l l l p l l l l h l c         ",
"        l p l l p l p l l p m Y K m l l p l l p p p p c p p m T Y b h h l p h p h h h l         ",
"      r h h l p l p c p c v  .9.9.] l p l p l l l p h h c b X.9.9.o.b l p l p l h p l p r       ",
"      r h h h h p l p z p M 9.9.9.9.v p p l p p p l p h v _ 9.6.9.9._ l p p l p p l l p r       ",
"      r p p h h p p p p p M 6.9.9.9.z p h h p h p l p l ~ 9.9.9.9.9.9./ l p p l p l p p r       ",
"      r h h h p p l l p p n 9.9.9.9.z p p h h h p p h U 9.9.9.9.9.9.9.9.T p p l p p p l r       ",
"      r p p p p h p p y h n 9.9.9.9.j p p y p p p p J 8.8.8.9.8.9.9.9.9.8.J h h h h p p r       ",
"      r p p p p p p h p p n 9.9.9.9.j p p p p p p D 2.9.9.9.9.9.9.9.9.9.9.2.B h p p p h r       ",
"      r p p p p p p p p p n 9.9.9.9.j p p p p p b ;.9.9.8.8.9.8.9.9.9.9.8.8.>.x p p i p r       ",
"      r p p p i p p i p p n 9.9.9.9.a p p p p p F 9.9.9.8.Q 9.8.9.9.P 9.8.8.9.F p i p p r       ",
"      r p p p p p p p p p x 9.9.9.9.a p p p p i n 2.9.9.W 6 9.9.9.4.3 W 9.9.9.n p p p p r       ",
"      r i i p p i i p i p x 9.9.9.9.j i i i p p 8 d I G $ 6 9.9.9.4.5 & S I f 8 i i p i r       ",
"      r i i p i i N ~ U h x 9.9.9.9.y h K ~ B i 0 % # # - k 9.9.9.2.q - # # $ 0 p p i p r       ",
"      r p i p p m :.2.2./ n 2.2.2.2.j ^ 4.2.>.M i 0 - > t x 4.2.4.>.j t > - , i i i i p r       ",
"      r i i p i D ;.>.>.>.( >.>.>.>.T >.>.>.>.D i i i i i x >.>.>.=.j i i i i i i i i i r       ",
"      r i i p i j  .=.=.=.=.-.-.-.-.-.-.=.=.O.j i i i i i k =.=.=.&.y i i i i i i i i i r       ",
"      r i i u u , s O.&.&.&.&.&.&.&.&.&.&.O.d > i i i i i z &.&.&.#.y i i i i i i i i i r       ",
"      r u i i u < % g #.%.%.%.%.%.%.%.%.#.g % < i i i i i z $.$.#.o.y i i i i i i i i i r       ",
"      r u i i u u , # Z +.+.+.+.+.+.+.+.A # , u i i u i i z ..| +.| y u u u i u u i u i r       ",
"      r u u u u i u > # H } } } } } } H # > u u r u u i r z { | | [ y r i i u i u u u u r       ",
"      r u u u u u u r : # L [ [ [ [ T # : e u i u u i u r j [ [ [ ] y u u u u u u i u u r       ",
"      r r u u u r u u e = & R ] ] W & = e u r r i r r i u < R ' ] T , u u r r u u r u u r       ",
"        i u r u u r u u e = 2 V N % % e r r r r u u u u r , 2 V V - e r r r r u r u u u         ",
"        i r u r r u r u r , % @ @ @ e r r r r r r r r r r e % @ @ = e r r e u r r r u i         ",
"        * r r r r u r u r r , ; = ; r r r r r r r u u r r r e = ; e r r r r r r u u r 2         ",
"          i r r r r r r r r r r r r r r r r r r r r r r r r r r e r r r r r r r r r u           ",
"          7 r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r 7           ",
"            r r r r r r r r e r r r r r r r r r r r r r r r r r r r r r r r r r r r             ",
"            r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r             ",
"              r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r               ",
"                  r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r                   ",
"                      r r r r r r r r r r r r r r r r r r r r r r r r r r                       ",
"                          r r r r r r r r r r r r r r r r r r r r r r                           ",
"                                          r r r r r r                                           ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]