table=[
"48 48 165 2 ",
"   c None",
".  c #004870",
"X  c #004871",
"o  c #004971",
"O  c #014971",
"+  c #004972",
"@  c #004A72",
"#  c #004A73",
"$  c #034B72",
"%  c #004B74",
"&  c #004B75",
"*  c #004C75",
"=  c #004C76",
"-  c #004C77",
";  c #004D77",
":  c #074E75",
">  c #004D78",
",  c #004E78",
"<  c #004E79",
"1  c #004F7A",
"2  c #0A5076",
"3  c #0C5177",
"4  c #00507C",
"5  c #00517E",
"6  c #01527F",
"7  c #0F5379",
"8  c #14577C",
"9  c #16597D",
"0  c #185A7E",
"q  c #005280",
"w  c #005380",
"e  c #005381",
"r  c #005482",
"t  c #005483",
"y  c #005584",
"u  c #005685",
"i  c #005686",
"p  c #005787",
"a  c #005788",
"s  c #005888",
"d  c #005889",
"f  c #00598A",
"g  c #00598B",
"h  c #005A8B",
"j  c #015A8B",
"k  c #055B8A",
"l  c #005A8C",
"z  c #005B8D",
"x  c #015B8D",
"c  c #035C8E",
"v  c #035D8E",
"b  c #055E8F",
"n  c #155D84",
"m  c #1C5D80",
"M  c #1D5E81",
"N  c #0B6292",
"B  c #0F6493",
"V  c #166793",
"C  c #146896",
"Z  c #1C6D99",
"A  c #1E6E9A",
"S  c #256486",
"D  c #266486",
"F  c #206388",
"G  c #296688",
"H  c #2B6889",
"J  c #2E6A8B",
"K  c #28688C",
"L  c #366F8F",
"P  c #37708F",
"I  c #22719C",
"U  c #26739E",
"Y  c #3B7392",
"T  c #3C7492",
"R  c #3D7493",
"E  c #3E7594",
"W  c #337BA3",
"Q  c #367DA5",
"!  c #407794",
"~  c #437996",
"^  c #457A97",
"/  c #4B7E9A",
"(  c #3D81A6",
")  c #54859F",
"_  c #4487AB",
"`  c #4587AB",
"'  c #4688AC",
"]  c #4889AD",
"[  c #4B8BAE",
"{  c #4D8CAF",
"}  c #5485A0",
"|  c #5486A2",
" . c #4E8DB0",
".. c #5B95B5",
"X. c #5D96B6",
"o. c #6792AA",
"O. c #6793AA",
"+. c #6796B0",
"@. c #779EB3",
"#. c #7BA1B5",
"$. c #7CA1B6",
"%. c #73A5C0",
"&. c #7EACC5",
"*. c #84A8BB",
"=. c #84B0C8",
"-. c #86B1C9",
";. c #8BB4CB",
":. c #8CB5CB",
">. c #95B3C4",
",. c #98B5C5",
"<. c #98B6C6",
"1. c #98BDD1",
"2. c #9BBFD2",
"3. c #A2BCCB",
"4. c #A3BDCC",
"5. c #A7C0CE",
"6. c #A2C3D5",
"7. c #A7C5D5",
"8. c #ADC4D1",
"9. c #AAC8D9",
"0. c #AFCBDB",
"q. c #B4C9D5",
"w. c #BCCFDA",
"e. c #B9D2DF",
"r. c #C1D3DC",
"t. c #CAD9E1",
"y. c #CADAE3",
"u. c #CCDBE3",
"i. c #CDDBE3",
"p. c #C9DCE7",
"a. c #CCDEE8",
"s. c #D0E0E9",
"d. c #D7E2E9",
"f. c #D4E2EB",
"g. c #D7E4EB",
"h. c #D9E4EA",
"j. c #DAE4EA",
"k. c #DEE7ED",
"l. c #DFE8ED",
"z. c #E1E9EE",
"x. c #E1EAEE",
"c. c #E1EBF1",
"v. c #E6EFF4",
"b. c #E7EFF4",
"n. c #E9F1F5",
"m. c #EEF2F5",
"M. c #EEF3F5",
"N. c #EEF4F7",
"B. c #F0F4F6",
"V. c #F0F4F7",
"C. c #F0F5F8",
"Z. c #F3F6F8",
"A. c #F6F8FA",
"S. c #F8FAFB",
"D. c #F9FAFB",
"F. c #F8FBFC",
"G. c #F9FBFC",
"H. c #FBFCFC",
"J. c #FBFCFD",
"K. c #FCFCFD",
"L. c #FCFDFD",
"P. c #FDFDFE",
"I. c #FDFEFE",
"U. c #FEFEFE",
"Y. c white",
"                                      l l z l l z l l z l                                       ",
"                                l l z l l z l l z l l z l l z l                                 ",
"                          l l z l l z l l z l l z l l z l l z l z l l                           ",
"                      z z z z z z z z z z z z z z z z z z z z z z z z z z                       ",
"                    l z l l l z l l z l l z l l z l l z l l z l z l l z l l                     ",
"                  z l z l l l z l l z l l z l l z l l z l l z l z l l z l l z                   ",
"                z z z z z z z z z z z z z z z z z z z z z z z z z z z z z z z z                 ",
"              l l z l z l l l z l l z l l z l l z l l z l l z l z l l z l l z l l               ",
"            z l l z l z l l l z l l z l l z l l z l l l l l z l z l l z l l z l l z             ",
"          z z z z z z z z z z z z z z z z z z z &.n.9.b l l z z z z z z z z z z z z z           ",
"        l l z l l z l z l l l z l l z l l z g $.Y.Y.Y.' l l z l z l l z l l z l l z l l         ",
"      l l l z l l z l z l l l z l l z l l z ..G.Y.Y.S.U l l z l z l l z l l z l l z l l z       ",
"      z z z z z z z z z z z z z z z z z l ` S.Y.Y.Y.=.b z z z z z z z z ; s z z z z z z z       ",
"    l z l l z l l z l z l l l z l l z l A V.Y.Y.Y.Y.Y.v.2.Q z l z l l l o o u l l z l l z l     ",
"    l z l l z l l z l z l l l z l l z l [ Y.Y.Y.Y.Y.Y.Y.Y.Y.0.A z l g g o o o r l z l l z l     ",
"    l l z z z z z z z z z z z z z z z z N s.Y.Y.Y.Y.Y.Y.Y.Y.Y.N.{ l l u o o o o 4 l z z z z     ",
"  l l z l l z l l z l z l l l z l l z l l F x.Y.Y.Y.k.8.S.Y.Y.Y.G.X.g r o o o . . ; g g z l l   ",
"  z z z z z z z z z z z z z z z z z z z l q J M.Y.Y.Y.Y G e.Y.Y.Y.A.` 4 o o o o o o ; g l l z   ",
"  l l z l l z l l z l z l l l z l l z l l g o E A.Y.Y.L . 4 =.Y.Y.Y.v.n . . o . . o . o u l l   ",
"z l l z l l z l l z l z l l l z l l l l l l 1 o ~ 5.o.o . o u ;.Y.Y.Y.>.. . o . . o . . o r l l ",
"z z z z z z z z z z z z z z z z z z q ; g l u o o o o o o o o k p.Y.Y.S.0 o o o o o o o o o 4 g ",
"z l l z l l z l l z l z l l l z l l o o o r l o o . . o . . o % ( Y.Y.Y.@.. o . . o . . o . . 1 ",
"z l l z l l z l l z l z l l l l l 4 o o o o 1 4 o . . o . . o . ; s.Y.Y.r.. o . . o . . o . . o ",
"z z z z z z z z z z z z z l l l g o o o o o o o o o o o o o o o o *.Y.Y.V.: o o o o o o o o o o ",
"z l l z l l z l l z z ;.n.1.l l 1 . o . . o . . o . . o . . o . . ) Y.Y.Y.m o . . o . . o . o o ",
"z l l z l l z l l z I Y.Y.Y.W u o . o . . o . . o . . o . . o . . ! Y.Y.Y.G o . . o . . o . . o ",
"z z z z z z z z z z U Y.Y.Y._ % o o o o o o o o o o o o o o o o . ^ Y.Y.Y.D o o o o o o o o o o ",
"z l l z l l z l l z C G.Y.Y.+.o . . o . . o . . o . . o . . o . . o.Y.Y.S.8 o . . o . . o . o o ",
"z l l z l l z l l z z c.Y.Y.4.o . . o . . o . . o . . o . . o . . 3.Y.Y.x.o o . . o . . o o o o ",
"  z z z z z z z l l z 6.Y.Y.B.3 o o o o o o o o o o o o o o o o 3 B.Y.Y.3.o o o o o o o o o o   ",
"  l l z l l z l l l g [ Y.Y.Y.@.. . o . . o . . o . . o . o o . #.Y.Y.Y./ . o . . o . . o o o   ",
"  l l z l l z l l l g l d.Y.Y.Z.H . o . . o . . o . . o . o o G V.Y.Y.h.o . o . . o . . o o o   ",
"    z z z z z z z z z l | Y.Y.Y.d.0 . o o o o o o o o o . . 0 h.Y.Y.Y.) o o o o o o o o o o     ",
"    l z l l z l l z l z l 7.Y.Y.Y.k.P . . o . . o . . o . L x.Y.Y.Y.4.o . . o . . o . . o o     ",
"    l z l l z l l z l z l B a.Y.Y.L.A.>.D o . . o . . D >.A.Y.Y.Y.u.8 . . . o . . o . . o o     ",
"      z l l z l l z l z l l V y.Y.Y.Y.Y.L.i.,.$.$.,.i.L.Y.Y.Y.Y.y.9 . o . . o . . o . . o       ",
"      z z z z z z z z s ; o o 2 ,.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.,.2 . o o o o o o o o o o o       ",
"        l l z l l z l z r o o o . T w.H.Y.Y.Y.Y.Y.Y.Y.Y.Y.w.T . . . . o . . o . o o o o         ",
"          z z z z z z z l u o o o o o G @.q.j.M.M.j.q.@.G . . o o o o o o o o o o o o           ",
"            z l l z l z g g g % . . o . . o . . o . . o . . o . o . . o . . o . o o             ",
"              l l z l z l l l g ; o o o o o . . o . . o . . o . o . . o o o o o o               ",
"                z z z z z z z z l 1 o o o o o o o o o o o o o o o o o o o o o o                 ",
"                  z l z l l l z l l 4 o . o . . o . . o . . o . o . . o . . o                   ",
"                    l z l l l z l l l q o o . . o . . o . . o . o . . o . o                     ",
"                      z z z z z z z z l r o o o o o o o o o o o o o o o o                       ",
"                          l l z l l z l l u o . o . . o . . o . o o o                           ",
"                                l l z l l l s % o . . o o o o o                                 ",
"                                      z z l l g ; o o o o                                       "
]