table=[
"48 48 114 2 ",
"   c None",
".  c #0B0B0B",
"X  c #0C0C0C",
"o  c gray5",
"O  c #0E0E0E",
"+  c gray6",
"@  c #101010",
"#  c #111111",
"$  c gray7",
"%  c #131313",
"&  c gray8",
"*  c #151515",
"=  c #161616",
"-  c gray9",
";  c #181818",
":  c #191919",
">  c gray10",
",  c #1B1B1B",
"<  c gray11",
"1  c #1D1D1D",
"2  c #1E1E1E",
"3  c gray12",
"4  c #202020",
"5  c gray13",
"6  c #222222",
"7  c #232323",
"8  c gray14",
"9  c #252525",
"0  c gray15",
"q  c #272727",
"w  c #282828",
"e  c gray16",
"r  c #2A2A2A",
"t  c gray17",
"y  c #2C2C2C",
"u  c #2D2D2D",
"i  c gray18",
"p  c #2F2F2F",
"a  c #313131",
"s  c #323232",
"d  c gray20",
"f  c #343434",
"g  c #353535",
"h  c gray21",
"j  c gray22",
"k  c gray23",
"l  c #3C3C3C",
"z  c gray24",
"x  c #414141",
"c  c gray26",
"v  c #434343",
"b  c #444444",
"n  c gray27",
"m  c #464646",
"M  c gray28",
"N  c #484848",
"B  c #494949",
"V  c gray29",
"C  c #4B4B4B",
"Z  c #4C4C4C",
"A  c #4E4E4E",
"S  c gray31",
"D  c #505050",
"F  c gray32",
"G  c #535353",
"H  c gray33",
"J  c #555555",
"K  c #565656",
"L  c gray34",
"P  c #585858",
"I  c gray35",
"U  c #5A5A5A",
"Y  c #5B5B5B",
"T  c gray36",
"R  c #5D5D5D",
"E  c gray37",
"W  c #5F5F5F",
"Q  c #606060",
"!  c gray38",
"~  c gray39",
"^  c #646464",
"/  c #656565",
"(  c gray40",
")  c #676767",
"_  c #686868",
"`  c DimGray",
"'  c #6A6A6A",
"]  c gray42",
"[  c #6C6C6C",
"{  c #6D6D6D",
"}  c gray43",
"|  c #6F6F6F",
" . c gray44",
".. c #717171",
"X. c #727272",
"o. c gray45",
"O. c #747474",
"+. c gray46",
"@. c #767676",
"#. c #777777",
"$. c gray47",
"%. c #797979",
"&. c #7B7B7B",
"*. c gray49",
"=. c #7E7E7E",
"-. c gray50",
";. c #808080",
":. c #818181",
">. c gray51",
",. c #838383",
"<. c #868686",
"1. c gray53",
"2. c gray54",
"3. c #909090",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                    ;.X.I C n n n n n n n n C n n n C n n n n n n n C L } O.                    ",
"                ;.L q r r r r y r y y y y y y y y r y y r y y y y y r r r q n -.                ",
"              -.y r y y y y y y y y y y y y y y y y y y y y y y y y y y y y r q }               ",
"            ;.q r y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y r q '             ",
"          -.r r r r r r r r r r r r r r r r r r y y r r r r r r r r r r r r r r r q O.          ",
"          I q r r r r y r r r r r r r r r r r q q r r r r r r r r r r r r r r r r r l           ",
"        &.q q q r r r r r r r r r r r r r q C ' ) I q r r r r r r q r r r r r r r r 7 '         ",
"        } 7 q q q r q q q q q q q l L 7 q 7 )     X.q q q n C q q q q q r q q r q q q W         ",
"        W q q q q q q q q q q 7 W     } r x         W 7 W     } q q q q q q q q q q q l         ",
"        S q q q 7 q q q 7 q q 7 !       '             '       &.7 q 7 7 7 q 7 q 7 q q a         ",
"        C 7 q 7 7 7 7 7 7 7 7 7 W                             O.2 7 7 7 7 7 7 7 q 7 7 y         ",
"        C 7 7 7 7 7 7 7 7 2 2 2 )                             } 7 2 2 7 7 7 7 7 7 q 7 y         ",
"        C 7 7 7 7 7 7 7 I ! W !                                 ) I ! ' 2 7 7 7 7 7 7 y         ",
"        C 2 2 7 2 2 2 a                                                 C 2 2 7 2 2 2 r         ",
"        n 2 2 2 2 2 2 l                                                 L 2 2 2 2 2 2 y         ",
"        n 2 2 2 2 2 2 2 I                   ;.} ' <.                  X.; 2 2 2 2 2 2 r         ",
"        n 2 2 2 2 2 2 ; ; '             &.) 7 ; ; 7 L )               q 2 2 ; 2 2 ; 2 r         ",
"        n 2 ; ; ; ; ; ; j             3.) ; 2 2 ; ; ; F <.            F ; ; ; 2 2 ; ; r         ",
"        n ; ; 2 ; ; l W               &.r ; ; ; ; 2 ; 2 O.              ! C ; ; ; ; ; r         ",
"        n ; ; ; ; ; I                 ' * * ; ; ; ; ; * L                 X.* ; ; ; ; r         ",
"        x ; ; * * * I                 } * ; * * ; ; * * W                 O.* * * * * q         ",
"        x * * * * * l }               } y * * * * * * * }               O.S * * * * * q         ",
"        x * * * $ * $ $ h             ;.W * $ * * * $ C <.            F $ * * * * * $ q         ",
"        x $ $ * * $ $ $ $ )             ) L q $ $ * L &.              7 $ $ * $ $ $ $ q         ",
"        x $ $ $ $ $ $ $ F                   2.' I }                   ) O $ $ $ $ $ $ 7         ",
"        x $ $ $ $ $ $ a                                                 C $ $ $ $ $ $ 7         ",
"        x $ $ $ $ O $ q                                                 x $ $ $ O $ O 7         ",
"        x O O O O O O O L O.' X.                                X.' O.X.O O O O O O O 7         ",
"        x O O O O O O O O . . . '                             X.$ . . O O O O O O O O 7         ",
"        x O O O O O O O O O O . L                             } O O O O O O O O O O . 7         ",
"        x O O O O O . O O O O . W       ;.            ;.      &.O . O O O . . O O O . 7         ",
"        F . . . O O O . . O . O I     X.* h         L $ W     X.O O O . O O . O O . O a         ",
"        ! O O O O O O . O O O . . r C . O . )     O.O . . j j . . O O O . O O . O O O S         ",
"        } O . O . . O O O . O O O . . O O O h O.O.F . . O O . O . O . O . O O . . O . W         ",
"          C O O . O O . O . . O O . . O . O . . O . O O O . O . . O . . O O . O O . r           ",
"          } * O O O O . O O O . . O O O . O O O O O O O O . O O O O O O O . O O O O )           ",
"            } O . O O . O O O . O O . . O O O O O . O O O O O O O . O O O O O O . I             ",
"              } $ . O O O . . O O O O O . . O O O O . O O . . O . O O . . O O O W               ",
"                } x O O O O O O O O O O O O O O . O O O . O O O O O O O . . a '                 ",
"                    ' I n h a a a h a a a a a a a a h a a a h a a a h x I !                     ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]