table=[
"48 48 128 2 ",
"   c None",
".  c #5F2E14",
"X  c #642B0E",
"o  c #612C11",
"O  c #7B3613",
"+  c #714420",
"@  c #7B5A37",
"#  c #7F5D39",
"$  c #7D6F4E",
"%  c #8E3D13",
"&  c #A54718",
"*  c #8C4720",
"=  c #904921",
"-  c #935326",
";  c #90552C",
":  c #9B5328",
">  c #9F612E",
",  c #956439",
"<  c #BA6431",
"1  c #BF763D",
"2  c #C2531A",
"3  c #D55C1E",
"4  c #D95C1D",
"5  c #C35C26",
"6  c #CC5D25",
"7  c #CC5F28",
"8  c #D45E23",
"9  c #DB5F20",
"0  c #CE6129",
"q  c #D66126",
"w  c #DA6124",
"e  c #D4642A",
"r  c #D9662B",
"t  c #D6692E",
"y  c #DC6B2D",
"u  c #CD6A33",
"i  c #D36C33",
"p  c #D96F31",
"a  c #C1793A",
"s  c #D67036",
"d  c #DD7333",
"f  c #D37639",
"g  c #D37A3F",
"h  c #DC7C3C",
"j  c #E26E2F",
"k  c #E3702F",
"l  c #E67331",
"z  c #EA7432",
"x  c #E47A36",
"c  c #EB7A35",
"v  c #E47D38",
"b  c #EC7E38",
"n  c #906D48",
"m  c #92744B",
"M  c #8B7352",
"N  c #AA7646",
"B  c #A47E56",
"V  c #C57D47",
"C  c #D47C43",
"Z  c #DB7E43",
"A  c #DD823F",
"S  c #E5843D",
"D  c #ED833C",
"F  c #EB883F",
"G  c #B38252",
"H  c #BA8F59",
"J  c #AD9666",
"K  c #CB844C",
"L  c #DB8343",
"P  c #DC8D45",
"I  c #C68C5A",
"U  c #D18D53",
"Y  c #D88A51",
"T  c #C2915C",
"R  c #CD995D",
"E  c #D59051",
"W  c #E48B44",
"Q  c #EC8C42",
"!  c #E49146",
"~  c #EC9246",
"^  c #E59548",
"/  c #EB964A",
"(  c #E69D4E",
")  c #EC9C4D",
"_  c #F09648",
"`  c #F09A4A",
"'  c #E79452",
"]  c #E99D50",
"[  c #E39559",
"{  c #EA9E5B",
"}  c #E7A352",
"|  c #E9A150",
" . c #E7AC5D",
".. c #EAA95C",
"X. c #C19B63",
"o. c #C6A46B",
"O. c #DCA966",
"+. c #EAAB64",
"@. c #ECAC6C",
"#. c #EDB36F",
"$. c #ECB675",
"%. c #ECB471",
"&. c #EFBB72",
"*. c #EEB876",
"=. c #ECB479",
"-. c #F0BF7A",
";. c #F1BF7D",
":. c #F3CC87",
">. c #F2C78A",
",. c #F3CF8B",
"<. c #F3CD92",
"1. c #F4D190",
"2. c #F4D097",
"3. c #F6D698",
"4. c #F6DB9A",
"5. c #F6DA9D",
"6. c #E4D3A1",
"7. c #F6DAA1",
"8. c #F7DCA2",
"9. c #F7DEA7",
"0. c #F8DFA7",
"q. c #F7E0A1",
"w. c #F9E4A7",
"e. c #F4E4AA",
"r. c #F8E1A9",
"t. c #F9E4A9",
"y. c #F9E5AB",
"u. c #FAE7AC",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                              e.                                                ",
"                                          4.q. .J                                               ",
"                                        w.,.} | ..$                                             ",
"                                      u.&.| | | ( +.                                            ",
"                                  1.t...) | | | ( ( O.                                          ",
"                                5.3.] ) ) ` ) ) / ^ ^ X.                                        ",
"                              t.;.~ ) ` ` ` ) / ^ ! P P                                         ",
"                            r.+.~ ~ / / _ / / ! W P a                                           ",
"                        <.8.' Q Q ~ ~ ~ ~ ~ Q S A >                                             ",
"                      7.>.Q Q Q Q _ Q Q Q Q W A +                                               ",
"                    r.@.S S D Q F F F F F S S @                                                 ",
"                  0.' S b D Q Q D D D D D D } *.$.%.$.%.%.#.#.&.-.:.                            ",
"              <.2.S x v b b b b D D D D D b c c x h x x v v v x x x W +.o.                      ",
"            8.=.d x x b b b b b D b b b b b c c x x x c x x x x x x x d S R                     ",
"          0.[ p d x z z c c c c b b c c c z c z z x x z z x l x x x l l d d E                   ",
"        6.L p t p j z z z z z z z z z z z l z l l l l l l l l z l l l l j j y K                 ",
"          M Z t p j j j l z l z z z z l l k l k k k k k k k k l j j l j j j y t ,               ",
"              Y r p j j j j j l z l l j j j y y y y y y y y y y j j j j j j y t s               ",
"                I r r p j j j j j j j j j y t t e e t e r e t t r y j j j j y t t ;             ",
"                  B s r r r y j j j j w y r L : * * * * = = = < i e r y j y y r e u             ",
"                      Z e e e r j j y w r e i I                   h t r r y t r e e             ",
"                        K 0 e e r r w y r e 0 0 U                 H e r q y r e e 0             ",
"                          B e 7 7 8 q r e e e 0 7 C m               C 8 e q e e 0 0 .           ",
"                            n i 6 e e e e e e 7 6 6 u G             L e e w e e e 6 o           ",
"                                g 6 8 8 8 8 q e 8 6 6 5             L 8 w w w q 8 6 o           ",
"                                  V 8 6 8 w w w 8 6 6               L 8 w w w w 8 8 o           ",
"                                    N e 8 8 8 8 8 8 O               h 8 4 j w w 8 8 o           ",
"                                      , p 3 3 8 3 &                 h 8 9 9 9 9 9 8 o           ",
"                                          f 3 3 2                   h 4 4 4 9 4 4 3 X           ",
"                                            a 8                     v 3 4 4 4 4 4 4 X           ",
"                                                                    - % % % % % % %             ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]