table=[
"48 48 150 2 ",
"   c None",
".  c #1F5A7C",
"X  c #274D63",
"o  c #215B7B",
"O  c #305E78",
"+  c #35617B",
"@  c #3A667E",
"#  c #2A6181",
"$  c #26678C",
"%  c #26698E",
"&  c #2B6B8E",
"*  c #3E6980",
"=  c #3F728C",
"-  c #276A90",
";  c #2D6D92",
":  c #20719F",
">  c #317196",
",  c #36769A",
"<  c #397699",
"1  c #3B799D",
"2  c #1F7FB6",
"3  c #2275A3",
"4  c #267AA9",
"5  c #377EA6",
"6  c #3D7DA0",
"7  c #476F85",
"8  c #497187",
"9  c #42728C",
"0  c #4C778E",
"q  c #4D788E",
"w  c #527487",
"e  c #427C9D",
"r  c #427FA2",
"t  c #3C83AB",
"y  c #2180B7",
"u  c #2484BB",
"i  c #2887BD",
"p  c #2588BF",
"a  c #2A89BF",
"s  c #4883A3",
"d  c #4187AF",
"f  c #4788AC",
"g  c #498AAE",
"h  c #458BB2",
"j  c #4C8EB3",
"k  c #5392B4",
"l  c #648FA6",
"z  c #6593AC",
"x  c #6894AB",
"c  c #6797B3",
"v  c #6A9BB5",
"b  c #2789C1",
"n  c #2C8CC3",
"m  c #318EC3",
"M  c #2D90C7",
"N  c #3491C6",
"B  c #3994C7",
"V  c #3595CB",
"C  c #3A96CA",
"Z  c #3799CF",
"A  c #3C99CD",
"S  c #3C9CD2",
"D  c #3CA5DE",
"F  c #3DA7E0",
"G  c #3FA8E1",
"H  c #4997C2",
"J  c #4B99C3",
"K  c #429BCE",
"L  c #4F9FCB",
"P  c #519BC4",
"I  c #429ED1",
"U  c #58A0C6",
"Y  c #5FA4CA",
"T  c #43A1D5",
"R  c #4AA3D4",
"E  c #43A6DC",
"W  c #4BA7DA",
"Q  c #44A9DF",
"!  c #4EA9DC",
"~  c #50A9DB",
"^  c #51AADB",
"/  c #50A9DC",
"(  c #52A9DC",
")  c #51ABDD",
"_  c #53ABDD",
"`  c #51ACDF",
"'  c #52ACDE",
"]  c #55ADDF",
"[  c #54ABDB",
"{  c #59AEDE",
"}  c #5DB1DF",
"|  c #60A4C9",
" . c #60A5CB",
".. c #63B2DE",
"X. c #73B2D3",
"o. c #41A7E0",
"O. c #43A9E0",
"+. c #42AAE1",
"@. c #40A9E2",
"#. c #41AAE3",
"$. c #44A9E0",
"%. c #45ABE1",
"&. c #47AAE0",
"*. c #44AAE2",
"=. c #43ABE4",
"-. c #42ACE4",
";. c #46ADE5",
":. c #4BADE1",
">. c #4FACE0",
",. c #4AAEE4",
"<. c #46AFE8",
"1. c #51ADE0",
"2. c #52ADE0",
"3. c #51AFE1",
"4. c #53AFE1",
"5. c #52AFE3",
"6. c #55AFE0",
"7. c #56AFE0",
"8. c #4BB0E6",
"9. c #47B1E9",
"0. c #4BB2E9",
"q. c #52B0E3",
"w. c #55B0E1",
"e. c #54B0E2",
"r. c #56B1E3",
"t. c #52B1E4",
"y. c #51B1E6",
"u. c #52B3E6",
"i. c #54B1E4",
"p. c #54B2E5",
"a. c #56B3E4",
"s. c #54B3E7",
"d. c #56B3E6",
"f. c #55B4E7",
"g. c #53B2E5",
"h. c #5BB3E4",
"j. c #54B4E8",
"k. c #56B5E8",
"l. c #55B6EA",
"z. c #5AB6E9",
"x. c #57B8EB",
"c. c #5DB9EB",
"v. c #62B6E4",
"b. c #65B9E6",
"n. c #69BBE6",
"m. c #65BCEB",
"M. c #6BBEEA",
"N. c #70BFEB",
"B. c #6DC0ED",
"V. c #71C0EB",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                    . : 3 3 3 3 3 4 4 4 4 o                                     ",
"                                    % 2 2 y y u u p p p b %                                     ",
"                                    - y y y u u u p p b b %                                     ",
"                                    ; u u y u p u b b b n %                                     ",
"                                    , n M M n a p b b b n &                                     ",
"                                    , n M N M V V M b b n &                                     ",
"                                    , n M N V V V Z Z M M ;                                     ",
"                                    1 N N M V V V Z Z A Z ;                                     ",
"                                    1 M N N V V Z Z Z A S ,                                     ",
"                                    1 N V V V Z Z Z A D D 1                                     ",
"                                    1 V V V Z A S S A D T e                                     ",
"                                    s V C Z A S S T D T T e                                     ",
"                                    s C Z A A I I T E W W s                                     ",
"          # 5 5 t t t t d h g h j j L Z A S I R ! ! ! >._ ..| Y  .U P P J J H H J J e           ",
"          ; y y p i a n n m N B V C C A S R ! ! ! _ 1.1.t.t.t.g.y.y.E E #.o.#.D D D f           ",
"          ; u u p i n m m N N C C A A T W ^ ^ _ _ ] ] ] t.i.i.i.i.k.>.%.Q #.#.#.#.G g           ",
"          > u u i a n m N B B C A K R ! ^ [ _ _ ] ] t.w.w.w.d.d.i.k.u.%.%.%.%.-.-.-.g           ",
"          > u i a m m m B B B A K R ! ^ [ [ ] ] ] w.r.h.h.h.k.k.k.x.x.:.%.%.%.-.;.-.j           ",
"          > i i a m m m B B A K R ! ^ ^ [ ] { } h.h.h.h.h.z.z.k.x.x.z.8.:.,.:.:.;.9.j           ",
"          > i a a N N B B A K K ^ ^ [ [ ] ] } } h.h.h.h.c.h.c.c.c.c.c.l.0.9.9.9.<.9.k           ",
"          , a n a N B B B K K R ^ [ [ { { } } h.h.h.h.c.c.c.c.c.c.c.x.x.8.9.8.9.9.9.k           ",
"          < a n m N B C K K R ^ [ [ ] { } } } v.v.v.h.b.c.c.b.c.c.c.c.x.u.8.0.8.9.0.k           ",
"          < a m N B B C K K R ^ [ [ [ } } h.v.v.v.v.b.b.b.b.b.b.c.c.c.x.u.0.u.0.0.0.k           ",
"          1 m N B K K K K R [ { { ....} } v.v.v.b.b.b.b.B.B.B.c.B.B.c.c.x.x.l.l.l.l.k           ",
"          X O + + @ + @ @ @ 7 7 8 8 X...v.v.v.v.b.b.m.n.B.X.0 0 q q 0 0 9 9 9 9 = =             ",
"                                    c v.v.v.b.b.n.n.n.m.B.z                                     ",
"                                    c v.v.b.n.n.n.m.n.m.B.z                                     ",
"                                    v b.b.b.n.N.N.n.N.N.B.c                                     ",
"                                    v b.b.n.n.n.N.N.N.M.B.z                                     ",
"                                    v b.n.n.N.N.V.N.N.M.B.x                                     ",
"                                    v n.n.n.N.N.V.V.N.N.B.z                                     ",
"                                    v b.n.M.M.M.N.V.B.B.B.c                                     ",
"                                    v n.n.n.M.M.B.B.B.B.B.z                                     ",
"                                    v b.b.n.M.M.M.B.B.B.B.c                                     ",
"                                    v v.b.b.m.M.M.M.m.B.B.z                                     ",
"                                    v v.c.b.b.m.m.m.m.m.m.z                                     ",
"                                    v b.b.b.b.m.m.m.m.m.B.z                                     ",
"                                    w l z z x x x x x x z                                       ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]